update users set password_hash = '$2b$12$BuUTKl5ag2FeLbLabUG6t.B7QQsj4pqAWVtdNCRg7pv012Ol0lvXO' where user_name = 'admin';

update public_shells set json = '{\"kind\": \"Shell\", \"spec\": {\"runtime\": \"ClaudeCode\", \"supportModel\": [\"claude\"]}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"ClaudeCode\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}' where name = 'ClaudeCode' and namespace = 'default';

INSERT INTO `public_models` (`id`, `name`, `namespace`, `json`, `is_active`, `created_at`, `updated_at`)
VALUES
	('1', 'sina-glm-4.5(内网)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"sina-glm-4.5\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"sina-glm-4.5(内网)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('2', 'wecode-claude-sina-glm-4.5(内网)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"claude\", \"api_key\": \"sk-wecode-proxy-claude-code-sk\", \"base_url\": \"https://ccr-copilot.weibo.com\", \"model_id\": \"wecode,sina-glm-4.5\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"wecode-claude-sina-glm-4.5(内网)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('3', 'thudm-glm-4.5(国内)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"thudm-glm-4.5\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"thudm-glm-4.5(国内)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('4', 'huoshan-deepseek-v3(国内)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"deepseek-chat\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"huoshan-deepseek-v3(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('5', 'ali-deepseek-v3.1(国内)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"ali-deepseek-v3.1\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"ali-deepseek-v3.1(国内)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:45', '2025-10-12 11:08:45'),	
	('6', 'ali-qwen3-coder-plus(国内)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"ali-qwen3-coder-plus\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"ali-qwen3-coder-plus(国内)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('7', 'openai-o3(海外)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"o3\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"openai-o3(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('8', 'wecode-claude3.5(海外)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"claude\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com\", \"model_id\": \"claude-3-5-sonnet-20241022\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"wecode-claude3.5(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('9', 'wecode-claude3.7(海外)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"claude\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com\", \"model_id\": \"claude-3-7-sonnet-20250219\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"wecode-claude3.7(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('10', 'wecode-claude-sonnet-4(海外)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"claude\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com\", \"model_id\": \"claude-sonnet-4-20250514\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"wecode-claude-sonnet-4(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('11', 'wecode-claude-opus-4.1(海外)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"claude\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com\", \"model_id\": \"claude-opus-4-1-20250805\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"wecode-claude-opus-4.1(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:44', '2025-10-12 11:08:44'),
	('12', 'wecode-gpt-4.1(海外)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"gpt-4.1\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"wecode-gpt-4.1(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:45', '2025-10-12 11:08:45'),
	('13', 'wecode-gpt-4.1-mini(海外)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"gpt-4.1-mini\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"wecode-gpt-4.1-mini(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:45', '2025-10-12 11:08:45'),
	('14', 'openai-gpt-5(海外)', 'default', '{\"kind\": \"Model\", \"spec\": {\"modelConfig\": {\"env\": {\"model\": \"openai\", \"api_key\": \"${WECODE_USER_API_KEY}\", \"base_url\": \"https://copilot.weibo.com/v1\", \"model_id\": \"gpt-5-2025-08-07\"}}}, \"status\": {\"state\": \"Available\"}, \"metadata\": {\"name\": \"openai-gpt-5(海外)\", \"namespace\": \"default\"}, \"apiVersion\": \"agent.wecode.io/v1\"}', '1', '2025-10-12 11:08:45', '2025-10-12 11:08:45');
