# SPDX-FileCopyrightText: 2025 Weibo, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""
Device model for wecode-cli connections.

Devices represent local development environments running wecode-cli
that connect to Wegent server via WebSocket for remote chat capabilities.
"""

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.db.base import Base

# Device status constants
DEVICE_STATUS_ONLINE = "online"
DEVICE_STATUS_OFFLINE = "offline"
DEVICE_STATUS_BUSY = "busy"


class Device(Base):
    """Device model for wecode-cli connections."""

    __tablename__ = "devices"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    # UUID generated by CLI on first connection
    device_id = Column(String(64), unique=True, nullable=False, index=True)
    # User-defined device name
    name = Column(String(128), nullable=False)
    # Device type: wecode-cli, cursor, etc.
    device_type = Column(String(32), nullable=False, default="wecode-cli")
    # Connection status: online, offline, busy
    status = Column(String(16), nullable=False, default=DEVICE_STATUS_OFFLINE)
    # Current workspace path on the device
    workspace_path = Column(String(512), nullable=True)
    # Socket.IO session ID for message routing
    socket_sid = Column(String(64), nullable=True)
    # Device metadata (version, capabilities, OS, etc.)
    metadata_json = Column(Text, nullable=True)
    # Timestamps
    last_seen_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, nullable=False, default=func.now())
    updated_at = Column(
        DateTime, nullable=False, default=func.now(), onupdate=func.now()
    )

    # Relationships
    user = relationship("User", back_populates="devices")

    __table_args__ = (
        {
            "sqlite_autoincrement": True,
            "mysql_engine": "InnoDB",
            "mysql_charset": "utf8mb4",
            "mysql_collate": "utf8mb4_unicode_ci",
        },
    )
