use std::sync::Arc;

use brz_http_server::{RegistryError, Router};

use crate::config::{AuthConfig, DatabaseConfig};
use crate::mysql;

/// Shared state owned by the public Rust Backend implementation.
///
/// It carries the general-purpose dependencies every protected route needs:
/// the JWT configuration and the process-wide MySQL pool. Private
/// applications retain this state (through `Arc<AppState>`) and add only their
/// own internal adapters instead of duplicating these.
#[derive(Debug)]
#[non_exhaustive]
pub struct AppState {
    /// Source-compatible JWT configuration (`settings.SECRET_KEY`,
    /// `settings.JWT_LEGACY_SECRET_KEYS`, `settings.ALGORITHM`).
    pub auth: AuthConfig,
    /// The single lazily-connected MySQL pool for the process.
    pub mysql: brz_mysql::MysqlService,
}

impl AppState {
    /// Builds the state from explicit dependencies.
    #[must_use]
    pub fn new(auth: AuthConfig, mysql_pool: brz_mysql::MysqlService) -> Self {
        Self {
            auth,
            mysql: mysql_pool,
        }
    }

    /// Builds the state from the source-compatible environment.
    ///
    /// # Errors
    ///
    /// Returns an error when `DATABASE_URL` is missing or malformed.
    pub fn from_env() -> Result<Self, crate::BoxError> {
        let database = DatabaseConfig::from_env()?;
        let pool = mysql::connect(&database.mysql_url())?;
        Ok(Self::new(AuthConfig::from_env(), pool))
    }
}

/// Public API state and macro-exported routes.
pub struct Application {
    /// The shared public state.
    pub state: Arc<AppState>,
    /// The routes exported by the public API group.
    pub routes: Router,
}

impl Application {
    /// Collects the public API group generated by `brz-http-server` macros.
    ///
    /// # Errors
    ///
    /// Returns an error when exported route declarations conflict.
    pub fn build(state: Arc<AppState>) -> Result<Self, RegistryError> {
        let routes = brz_http_server::handlers!(state = Arc::clone(&state))?;
        Ok(Self { state, routes })
    }

    /// Adds application-specific routes without making the public crate depend
    /// on private state or modules.
    #[must_use]
    pub fn with_routes(self, routes: Router) -> Self {
        Self {
            state: self.state,
            routes: self.routes.merge(routes),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn state() -> AppState {
        AppState::new(
            AuthConfig {
                jwt_key: "backend-rs-test-key".to_owned(),
                legacy_jwt_keys: Vec::new(),
                algorithm: "HS256".to_owned(),
            },
            mysql::connect("mysql://user:pw@127.0.0.1:3306/db").expect("lazy pool needs no server"),
        )
    }

    #[tokio::test]
    async fn application_retains_public_state() {
        let state = Arc::new(state());
        let application = Application::build(Arc::clone(&state)).expect("routes build");

        assert!(Arc::ptr_eq(&application.state, &state));
    }
}
