# SPDX-FileCopyrightText: 2026 Weibo, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""Import all collectors to trigger decorator registration."""

from knowledge_engine.stat.collectors.collaboration import (
    approval_efficiency,
    cross_org_access,
    invitation_chain,
    kb_member_scale,
    permission_change_trend,
    share_link_usage,
)
from knowledge_engine.stat.collectors.content_quality import (
    content_freshness,
    duplicate_doc_suspect,
    kb_content_freshness,
    kb_thin_doc_rate,
)
from knowledge_engine.stat.collectors.dashboard import (
    collect_global_totals,
    collect_kb_daily_stats,
    collect_period_and_daily,
)
from knowledge_engine.stat.collectors.deep_analysis import (
    doc_lifecycle_trace,
    doc_value_ranking,
    kb_growth_curve,
    kb_health_score,
    rag_head_verify_rate,
    user_pattern_evolution,
    user_segmentation,
)
from knowledge_engine.stat.collectors.doc_management import (
    doc_chunk_count_distribution,
    doc_chunk_strategy,
    doc_folder_depth,
    doc_index_failure_rate,
    doc_index_status,
    doc_size_distribution,
    doc_summary_status,
    doc_update_frequency,
    doc_upload_trend,
    kb_avg_doc_length,
)
from knowledge_engine.stat.collectors.lifecycle import (
    kb_abandon_rate,
    kb_activity,
    kb_config_sanity,
    kb_creation_trend,
    kb_retrieval_config,
    kb_sharing,
    kb_size_distribution,
    kb_topic_distribution,
)
from knowledge_engine.stat.collectors.prometheus import (
    prom_active_conversions,
    prom_callback_success_rate,
    prom_conversion_duration,
    prom_conversion_success_rate,
)
from knowledge_engine.stat.collectors.retrieval import (
    answer_adoption_rate,
    chunks_count_distribution,
    doc_read_count,
    doc_reference_count,
    kb_active_users,
    kb_head_frequency,
    kb_rag_head_ratio,
    kb_retrieval_hit_rate,
    kb_retrieval_mode_dist,
    kb_zero_chunk_rate,
    rag_call_frequency,
    rag_call_limit,
    rag_vs_head_ratio,
    restricted_mode_usage,
    retrieval_mode_distribution,
    selected_documents_usage,
)
from knowledge_engine.stat.collectors.sys_ops import (
    attachment_storage,
    doc_index_storage_view,
    storage_usage,
)
from knowledge_engine.stat.collectors.user_behavior import (
    cross_kb_query_user,
    doc_uploader_ranking,
    kb_creator_ranking,
    restricted_analyst_usage,
    retrieval_active_user,
    user_first_kb_usage,
    user_kb_binding,
    user_participation_summary,
    user_permission_distribution,
    user_rag_head_preference,
)

__all__ = [
    "kb_creation_trend",
    "kb_activity",
    "kb_topic_distribution",
    "kb_retrieval_config",
    "kb_size_distribution",
    "kb_abandon_rate",
    "kb_sharing",
    "collect_global_totals",
    "collect_period_and_daily",
    "collect_kb_daily_stats",
    "kb_health_score",
    "doc_value_ranking",
    "doc_lifecycle_trace",
    "user_pattern_evolution",
    "kb_growth_curve",
    "rag_head_verify_rate",
    "user_segmentation",
    "kb_member_scale",
    "invitation_chain",
    "share_link_usage",
    "approval_efficiency",
    "cross_org_access",
    "permission_change_trend",
    "kb_creator_ranking",
    "doc_uploader_ranking",
    "cross_kb_query_user",
    "retrieval_active_user",
    "user_rag_head_preference",
    "user_kb_binding",
    "user_permission_distribution",
    "restricted_analyst_usage",
    "user_first_kb_usage",
    "user_participation_summary",
    "rag_call_frequency",
    "kb_head_frequency",
    "rag_vs_head_ratio",
    "doc_reference_count",
    "doc_read_count",
    "retrieval_mode_distribution",
    "restricted_mode_usage",
    "rag_call_limit",
    "selected_documents_usage",
    "chunks_count_distribution",
    "kb_active_users",
    "kb_rag_head_ratio",
    "kb_zero_chunk_rate",
    "kb_retrieval_mode_dist",
    "kb_retrieval_hit_rate",
    "answer_adoption_rate",
    "doc_upload_trend",
    "doc_index_status",
    "doc_index_failure_rate",
    "doc_size_distribution",
    "doc_update_frequency",
    "doc_folder_depth",
    "doc_chunk_strategy",
    "doc_chunk_count_distribution",
    "kb_avg_doc_length",
    "doc_summary_status",
    "storage_usage",
    "attachment_storage",
    "doc_index_storage_view",
    "prom_conversion_success_rate",
    "prom_conversion_duration",
    "prom_active_conversions",
    "prom_callback_success_rate",
    "kb_thin_doc_rate",
    "content_freshness",
    "kb_content_freshness",
    "duplicate_doc_suspect",
    "kb_config_sanity",
]
