# -*- mode: python ; coding: utf-8 -*-
# SPDX-FileCopyrightText: 2025 Weibo, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""
PyInstaller spec file for wegent-executor local mode binary.

This spec file is auto-generated by build_local.py but can be customized
for advanced build configurations.

Usage:
    cd executor/build
    pyinstaller wegent-executor.spec
"""

from PyInstaller.utils.hooks import collect_data_files, collect_submodules
import sys
import os

# Get paths
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(SPEC))))
executor_dir = os.path.join(project_root, 'executor')
shared_dir = os.path.join(project_root, 'shared')

# Analysis
a = Analysis(
    [os.path.join(executor_dir, 'main.py')],
    pathex=[project_root],
    binaries=[],
    datas=[
        (executor_dir, 'executor'),
        (shared_dir, 'shared'),
    ],
    hiddenimports=[
        'executor.modes.local',
        'executor.modes.local.runner',
        'executor.modes.local.websocket_client',
        'executor.modes.local.heartbeat',
        'executor.modes.local.progress_reporter',
        'executor.modes.local.handlers',
        'executor.modes.local.events',
        'executor.agents.claude_code.claude_code_agent',
        'socketio',
        'engineio',
        'aiohttp',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'docker',
        'kubernetes',
        'uvicorn',
        'fastapi',
        'starlette',
    ],
    noarchive=False,
)

# PYZ archive
pyz = PYZ(a.pure)

# Executable
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='wegent-executor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch='universal2' if sys.platform == 'darwin' else None,
    codesign_identity=None,
    entitlements_file=None,
)
