// SPDX-FileCopyrightText: 2025 Weibo, Inc.
//
// SPDX-License-Identifier: Apache-2.0

//
// Parse structured clarification questions from Markdown content generated by
// the "spec-ghost" (Requirements Analyst) agent.
//
// The Markdown format this parser expects is defined in the spec-ghost system prompt:
//   backend/init_data/02-public-resources.yaml  (kind: Ghost, name: spec-ghost)
//
// Key format rules from the spec:
//   - Section header: `## 🤔 Clarification Questions`
//   - Question header: `### Q{n}: {question_text}`
//   - Type declaration: `**Type**: single_choice | multiple_choice | text_input`
//   - Option format:    `- [✓] \`value\` - Label (recommended)` or `- [ ] \`value\` - Label`
//   - The entire section may be wrapped in a ```markdown code block.
//

import { marked, type Token, type Tokens } from 'marked'
import type { ClarificationData, ClarificationOption } from '@/types/api'

export interface ParsedClarification {
  data: ClarificationData
  prefixText: string
  suffixText: string
}

// ============================================================================
// Constants
// ============================================================================

/** Keywords that identify a clarification section heading (lowercase). */
const CLARIFICATION_KEYWORDS = [
  '智能追问',
  '澄清问题',
  '澄清',
  'clarification questions',
  'clarification',
  'smart follow-up questions',
  'smart follow-up',
  'smart followup questions',
  'smart followup',
]

/** Emoji prefixes that may appear before the keyword in a heading. */
const HEADER_EMOJIS = ['💬', '🤔']

/** Optional Chinese prefix "需求" that may precede the keyword. */
const CHINESE_OPTIONAL_PREFIX = '需求'

/** Labels that denote the question type field (lowercase). */
const TYPE_LABELS = ['type', '类型']

/** Labels that mark an option as recommended (lowercase). */
const RECOMMENDED_LABELS = ['recommended', '推荐']

/** Custom checkbox markers that indicate a recommended option. */
const RECOMMENDED_CHECKBOX_MARKS = ['✓', 'x', '*']

/** Separator between option value and label in list items. */
const OPTION_VALUE_LABEL_SEPARATOR = ' - '

/** Prefix for generated question IDs. */
const QUESTION_ID_PREFIX = 'q'

/** Colon-like characters used after labels (Type:, 类型：). */
const COLON_CHARS_PATTERN = /^[:\s：]+/

/** Pattern to extract question number and text from a plain string. */
const QUESTION_HEADER_PATTERN = /^Q?(\d+)[:.：]\s*(.+)/i

/** Separator for joining prefix/suffix parts. */
const TEXT_JOIN_SEPARATOR = '\n\n'

type QuestionType = 'single_choice' | 'multiple_choice' | 'text_input'

// ============================================================================
// Inline token helpers
// ============================================================================

/**
 * Flatten nested inline tokens into a flat array of leaf tokens.
 * Skips parent tokens that have children to avoid double-processing.
 *
 * Input example (marked inline tokens for `[✓] \`react\` - React`):
 *   [text("[✓] `react` - React", tokens: [text("[✓] "), codespan("react"), text(" - React")])]
 * Output:
 *   [text("[✓] "), codespan("react"), text(" - React")]
 */
function flattenInlineTokens(tokens: Token[]): Token[] {
  const result: Token[] = []
  for (const t of tokens) {
    if ('tokens' in t && Array.isArray(t.tokens) && t.tokens.length > 0) {
      result.push(...flattenInlineTokens(t.tokens))
    } else {
      result.push(t)
    }
  }
  return result
}

// ============================================================================
// Heading detection
// ============================================================================

/**
 * Check if a heading token's text matches a clarification header.
 *
 * Input examples:
 *   "🤔 Clarification Questions" → true
 *   "💬 智能追问"                → true
 *   "需求澄清问题"              → true
 *   "## Some Other Heading"      → false
 */
function isClarificationHeading(text: string): boolean {
  let normalized = text.trim().toLowerCase()

  for (const emoji of HEADER_EMOJIS) {
    if (normalized.startsWith(emoji)) {
      normalized = normalized.slice(emoji.length).trim()
      break
    }
  }

  if (normalized.startsWith(CHINESE_OPTIONAL_PREFIX)) {
    normalized = normalized.slice(CHINESE_OPTIONAL_PREFIX.length).trim()
  }

  return CLARIFICATION_KEYWORDS.some(kw => normalized === kw)
}

// ============================================================================
// Question header parsing
// ============================================================================

/**
 * Parse question number and text from a heading token's plain text.
 * Uses a single regex for string feature extraction (not structure parsing).
 *
 * Input examples:
 *   "Q1: What framework do you prefer?"  → { number: 1, text: "What framework do you prefer?" }
 *   "Q2. Which database?"                → { number: 2, text: "Which database?" }
 *   "3: Select a language"               → { number: 3, text: "Select a language" }
 *   "Not a question"                     → null
 */
function parseQuestionHeader(text: string): { number: number; text: string } | null {
  const cleaned = text.replace(/\*\*/g, '').trim()
  const match = cleaned.match(QUESTION_HEADER_PATTERN)
  if (!match) return null
  return { number: parseInt(match[1]), text: match[2].trim() }
}

/**
 * Parse question number and text from a paragraph token's inline tokens.
 * Handles bold format where marked splits `**Q1:** text` into strong + text tokens.
 *
 * Input examples (paragraph inline tokens):
 *   [strong("Q1:"), text(" What framework?")]  → { number: 1, text: "What framework?" }
 *   [text("Q1: What framework?\nType: ...")]   → { number: 1, text: "What framework?" }
 */
function parseQuestionHeaderFromParagraph(
  paragraph: Tokens.Paragraph
): { number: number; text: string } | null {
  const flat = flattenInlineTokens(paragraph.tokens || [])
  if (flat.length === 0) return null

  // Concatenate leading text tokens until we have enough to parse a header
  let accumulated = ''
  for (const t of flat) {
    if (t.type !== 'text') break
    accumulated += t.text || ''
    // Only need the first line
    const firstLine = accumulated.split('\n')[0]
    const result = parseQuestionHeader(firstLine)
    if (result) return result
  }

  return null
}

// ============================================================================
// Question type parsing
// ============================================================================

/** Classify a raw type string into a QuestionType enum value. */
function classifyType(raw: string): QuestionType {
  const v = raw.toLowerCase()
  if (v.includes('single')) return 'single_choice'
  if (v.includes('multi')) return 'multiple_choice'
  if (v.includes('text')) return 'text_input'
  return 'single_choice'
}

/**
 * Extract question type from flattened inline tokens.
 * Walks leaf tokens looking for a type label followed by its value.
 *
 * Input examples (flattened leaf tokens):
 *   [text("Type"), text(": single_choice")]           → "single_choice"
 *   [text("Q1: ...\nType: multiple_choice")]          → "multiple_choice"
 *   [text("类型"), text("：text_input")]               → "text_input"
 */
function parseQuestionTypeFromTokens(tokens: Token[]): QuestionType | null {
  const flat = flattenInlineTokens(tokens)

  for (let i = 0; i < flat.length; i++) {
    const t = flat[i]
    if (t.type !== 'text' || !t.text) continue

    const lines = t.text.split('\n')
    for (const line of lines) {
      const trimmed = line.trim().toLowerCase()
      const matchedLabel = TYPE_LABELS.find(label => trimmed.startsWith(label))
      if (!matchedLabel) continue

      // Type label found — value may be in the same text or the next token
      const rest = line.trim().slice(matchedLabel.length)
      const afterColon = rest
        .replace(COLON_CHARS_PATTERN, '')
        .trim()
        .split(/[\s\n]/)[0]
      if (afterColon) return classifyType(afterColon)

      // Value in next token: text("Type") followed by text(": single_choice")
      const next = flat[i + 1]
      if (next?.type === 'text' && next.text) {
        const nextValue = next.text
          .replace(COLON_CHARS_PATTERN, '')
          .trim()
          .split(/[\s\n]/)[0]
        if (nextValue) return classifyType(nextValue)
      }
    }
  }

  return null
}

/**
 * Extract question type from a paragraph token.
 *
 * Input examples (paragraph.text):
 *   "**Type**: single_choice"                         → "single_choice"
 *   "Q1: What framework?\nType: single_choice"        → "single_choice"
 *   "**类型**: multiple_choice\n**Options**:"          → "multiple_choice"
 */
function parseQuestionTypeFromParagraph(paragraph: Tokens.Paragraph): QuestionType | null {
  return parseQuestionTypeFromTokens(paragraph.tokens || [])
}

/** Check if a paragraph contains a type declaration (used for token grouping). */
function paragraphHasType(paragraph: Tokens.Paragraph): boolean {
  return parseQuestionTypeFromParagraph(paragraph) !== null
}

// ============================================================================
// Option parsing
// ============================================================================

/**
 * Parse a list item into a clarification option using marked's token structure.
 *
 * Input examples (list item text / token structure):
 *   task=true,  checked=true:  [checkbox, codespan("react"), text(" - React")]
 *   task=true,  checked=false: [checkbox, codespan("vue"),   text(" - Vue")]
 *   task=false (custom [✓]):   [text("[✓] "), codespan("react"), text(" - React (recommended)")]
 *   task=false (no backticks):  [text("[✓] option1 - Option 1 (recommended)")]
 */
function parseOptionFromListItem(item: Tokens.ListItem): ClarificationOption | null {
  let isRecommended = item.task && item.checked === true
  const flat = flattenInlineTokens(item.tokens)

  // For non-task items, check for custom checkbox markers [✓], [*]
  let valueStartIdx = 0
  if (!item.task) {
    const firstText = flat.find((t): t is Tokens.Text => t.type === 'text')
    if (firstText?.text) {
      const text = firstText.text
      if (text.startsWith('[')) {
        const closeBracket = text.indexOf(']')
        if (closeBracket !== -1) {
          const mark = text.slice(1, closeBracket).trim()
          if (RECOMMENDED_CHECKBOX_MARKS.some(m => mark.toLowerCase() === m.toLowerCase())) {
            isRecommended = true
          }
          valueStartIdx = -1 // Signal to skip this text token's checkbox prefix
        }
      }
    }
  } else {
    // For task items, skip the checkbox token
    valueStartIdx = flat.findIndex(t => t.type !== 'checkbox')
    if (valueStartIdx === -1) return null
  }

  // Walk tokens to extract value (codespan or text before separator) and label (text after separator)
  let value: string | null = null
  const labelParts: string[] = []
  let foundDash = false

  for (let i = Math.max(0, valueStartIdx); i < flat.length; i++) {
    const t = flat[i]

    if (t.type === 'checkbox') continue

    if (t.type === 'codespan' && !value) {
      value = t.text || ''
      continue
    }

    if (t.type === 'text' && t.text) {
      let text = t.text

      // Strip custom checkbox prefix from first text token
      if (i === 0 && valueStartIdx === -1 && text.startsWith('[')) {
        const afterBracket = text.indexOf(']')
        if (afterBracket !== -1) {
          text = text.slice(afterBracket + 1).trim()
        }
      }

      if (!value && !foundDash) {
        // No codespan found yet — value is text before first separator
        const dashIdx = text.indexOf(OPTION_VALUE_LABEL_SEPARATOR)
        if (dashIdx !== -1) {
          value = text.slice(0, dashIdx).trim()
          labelParts.push(text.slice(dashIdx + OPTION_VALUE_LABEL_SEPARATOR.length))
          foundDash = true
        } else {
          value = text.trim()
        }
      } else if (value && !foundDash) {
        // Value found via codespan, looking for separator
        const dashIdx = text.indexOf(OPTION_VALUE_LABEL_SEPARATOR)
        if (dashIdx !== -1) {
          labelParts.push(text.slice(dashIdx + OPTION_VALUE_LABEL_SEPARATOR.length))
          foundDash = true
        }
      } else {
        // After the separator, everything is label
        labelParts.push(text)
      }
    }
  }

  if (!value) return null

  let label = labelParts.join('').trim()

  // Check for recommended marker in label text
  if (!isRecommended) {
    const labelLower = label.toLowerCase()
    if (RECOMMENDED_LABELS.some(r => labelLower.includes(r) || label.includes(r))) {
      isRecommended = true
    }
  }

  // Strip trailing (recommended) / (推荐) from label
  for (const r of RECOMMENDED_LABELS) {
    const suffix = `(${r})`
    if (label.toLowerCase().endsWith(suffix)) {
      label = label.slice(0, -suffix.length).trim()
      break
    }
  }

  return {
    value,
    label: label || value,
    recommended: isRecommended,
  }
}

// ============================================================================
// Token utilities
// ============================================================================

/** Sum the raw text length of tokens[start..end). */
function rawLength(tokens: Token[], start: number, end: number): number {
  let len = 0
  for (let i = start; i < end; i++) {
    len += tokens[i].raw.length
  }
  return len
}

// ============================================================================
// Core parser
// ============================================================================

/**
 * Parse structured clarification data from a flat token array.
 *
 * Input example (full markdown):
 *   ## 🤔 Clarification Questions
 *
 *   ### Q1: What framework do you prefer?
 *   **Type**: single_choice
 *   **Options**:
 *   - [✓] `react` - React (recommended)
 *   - [ ] `vue` - Vue
 *
 *   ### Q2: Describe your requirements
 *   **Type**: text_input
 */
function parseFromTokens(
  tokens: Token[],
  originalContent: string,
  prefixOffset: number
): ParsedClarification | null {
  // Find the clarification heading
  let headerIdx = -1
  let headerDepth = 0
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i]
    if (token.type === 'heading' && isClarificationHeading(token.text)) {
      headerIdx = i
      headerDepth = token.depth
      break
    }
  }

  if (headerIdx === -1) return null

  const prefixEnd = prefixOffset + rawLength(tokens, 0, headerIdx)
  const prefixText = originalContent.substring(0, prefixEnd).trim()

  // Group tokens after the header into question blocks
  const bodyTokens = tokens.slice(headerIdx + 1)
  const questionGroups: Token[][] = []
  let currentGroup: Token[] | null = null

  for (const token of bodyTokens) {
    const isQuestionHeading =
      token.type === 'heading' &&
      token.depth > headerDepth &&
      parseQuestionHeader(token.text) !== null

    const isQuestionParagraph =
      token.type === 'paragraph' &&
      parseQuestionHeaderFromParagraph(token as Tokens.Paragraph) !== null

    if (isQuestionHeading || isQuestionParagraph) {
      if (currentGroup) questionGroups.push(currentGroup)
      currentGroup = [token]
    } else if (currentGroup) {
      if (token.type === 'list' || token.type === 'space') {
        currentGroup.push(token)
      } else if (token.type === 'paragraph' && paragraphHasType(token as Tokens.Paragraph)) {
        currentGroup.push(token)
      } else {
        questionGroups.push(currentGroup)
        currentGroup = null
      }
    }
  }
  if (currentGroup) questionGroups.push(currentGroup)

  // Parse each question group
  const questions: ClarificationData['questions'] = []

  for (const group of questionGroups) {
    const firstToken = group[0]

    let questionInfo: { number: number; text: string } | null = null
    let questionType: QuestionType | null = null

    if (firstToken.type === 'heading') {
      questionInfo = parseQuestionHeader(firstToken.text)
      for (const t of group.slice(1)) {
        if (t.type === 'paragraph') {
          questionType = parseQuestionTypeFromParagraph(t as Tokens.Paragraph)
          if (questionType) break
        }
      }
    } else if (firstToken.type === 'paragraph') {
      questionInfo = parseQuestionHeaderFromParagraph(firstToken as Tokens.Paragraph)
      questionType = parseQuestionTypeFromParagraph(firstToken as Tokens.Paragraph)
      if (!questionType) {
        for (const t of group.slice(1)) {
          if (t.type === 'paragraph') {
            questionType = parseQuestionTypeFromParagraph(t as Tokens.Paragraph)
            if (questionType) break
          }
        }
      }
    }

    if (!questionInfo || !questionType) continue

    const questionId = `${QUESTION_ID_PREFIX}${questionInfo.number}`

    if (questionType === 'text_input') {
      questions.push({
        question_id: questionId,
        question_text: questionInfo.text,
        question_type: 'text_input',
      })
      continue
    }

    // Extract options from list tokens
    const options: ClarificationOption[] = []
    for (const t of group) {
      if (t.type === 'list') {
        for (const item of (t as Tokens.List).items) {
          const option = parseOptionFromListItem(item)
          if (option) options.push(option)
        }
      }
    }

    if (options.length > 0) {
      questions.push({
        question_id: questionId,
        question_text: questionInfo.text,
        question_type: questionType,
        options,
      })
    }
  }

  if (questions.length === 0) return null

  // Compute suffix
  const lastGroup = questionGroups[questionGroups.length - 1]
  const lastToken = lastGroup[lastGroup.length - 1]
  const lastTokenIdx = tokens.indexOf(lastToken)
  const contentEnd = prefixOffset + rawLength(tokens, 0, lastTokenIdx + 1)
  const suffixText = originalContent.substring(contentEnd).trim()

  return {
    data: { type: 'clarification', questions },
    prefixText,
    suffixText,
  }
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Parse markdown content to extract clarification questions.
 *
 * Uses marked.lexer() for structural tokenization instead of fragile regex patterns.
 * Supports flexible formats: with/without code blocks, emoji variations, different
 * header levels, heading-style and paragraph-style question headers.
 *
 * Input example (direct):
 *   "## 🤔 Clarification Questions\n\nQ1: Select framework\nType: single_choice\n- [✓] `react` - React\n- [ ] `vue` - Vue"
 *
 * Input example (code block wrapped):
 *   "Some prefix\n\n```markdown\n## Clarification Questions\n...\n```\n\nSome suffix"
 *
 * @returns Parsed clarification data with prefix/suffix text, or null if no clarification found
 */
export function parseMarkdownClarification(content: string): ParsedClarification | null {
  const tokens = marked.lexer(content)

  // Try direct parsing (clarification heading at top level)
  const directResult = parseFromTokens(tokens, content, 0)
  if (directResult) return directResult

  // Fallback: clarification inside a code block (```markdown ... ```)
  for (const token of tokens) {
    if (token.type === 'code' && token.text) {
      const innerTokens = marked.lexer(token.text)
      if (!innerTokens.some(t => t.type === 'heading' && isClarificationHeading(t.text))) continue

      const innerResult = parseFromTokens(innerTokens, token.text, 0)
      if (!innerResult) continue

      const codeBlockStart = content.indexOf(token.raw)
      const outerPrefix = content.substring(0, codeBlockStart).trim()
      const outerSuffix = content.substring(codeBlockStart + token.raw.length).trim()

      return {
        data: innerResult.data,
        prefixText: [outerPrefix, innerResult.prefixText].filter(Boolean).join(TEXT_JOIN_SEPARATOR),
        suffixText: [innerResult.suffixText, outerSuffix].filter(Boolean).join(TEXT_JOIN_SEPARATOR),
      }
    }
  }

  return null
}
