/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
    './wecode/**/*.{ts,tsx}',
    './node_modules/streamdown/dist/*.js',
  ],
  theme: {
    extend: {
      colors: {
        base: 'rgb(var(--color-bg-base) / <alpha-value>)',
        primary: 'rgb(var(--color-primary) / <alpha-value>)',
        'primary-contrast': 'rgb(var(--color-primary-contrast) / <alpha-value>)',
        'text-primary': 'rgb(var(--color-text-primary) / <alpha-value>)',
        'text-secondary': 'rgb(var(--color-text-secondary) / <alpha-value>)',
        'text-muted': 'rgb(var(--color-text-muted) / <alpha-value>)',
        background: 'rgb(var(--color-bg-base) / <alpha-value>)',
        surface: 'rgb(var(--color-bg-surface) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        hover: 'rgb(var(--color-bg-hover))',
        sidebar: 'rgb(var(--color-sidebar))',
        'sidebar-active': 'rgb(var(--color-sidebar-active) / <alpha-value>)',
        'sidebar-hover': 'rgb(var(--color-sidebar-hover))',
        'sidebar-text-primary': 'rgb(var(--color-sidebar-text-primary) / <alpha-value>)',
        'sidebar-text-secondary': 'rgb(var(--color-sidebar-text-secondary) / <alpha-value>)',
        'sidebar-text-muted': 'rgb(var(--color-sidebar-text-muted) / <alpha-value>)',
        'mobile-drawer': 'rgb(var(--color-mobile-drawer))',
        popover: 'rgb(var(--color-popover) / <alpha-value>)',
        'code-bg': 'rgb(var(--color-code-bg) / <alpha-value>)',
        'reasoning-standard': 'rgb(var(--color-reasoning-standard) / <alpha-value>)',
        'reasoning-ultra-start': 'rgb(var(--color-reasoning-ultra-start) / <alpha-value>)',
        'reasoning-ultra-end': 'rgb(var(--color-reasoning-ultra-end) / <alpha-value>)',
        'reasoning-ultra-text': 'rgb(var(--color-reasoning-ultra-text) / <alpha-value>)',
        'reasoning-contrast': 'rgb(var(--color-reasoning-contrast) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
      },
      zIndex: {
        chrome: 'var(--z-chrome)',
        popover: 'var(--z-popover)',
        modal: 'var(--z-modal)',
        critical: 'var(--z-critical)',
        system: 'var(--z-system)',
        'system-popover': 'var(--z-system-popover)',
      },
    },
  },
  plugins: [],
}
