export const DESKTOP_CHECKPOINTS = [
  'workspace-tabs',
  'priority-filter',
  'telemetry-consent',
  'automation-lifecycle',
  'project-automation',
  'offline-local-project-space',
  'plugin-auto-update',
  'model-routing',
  'permission-modes',
  'core-task-flow',
  'context-compaction',
  'runtime-task-queue',
  'split-workbench',
  'window-lifecycle',
  'goal-lifecycle',
  'supervisor-lifecycle',
  'resilience',
  'conversation-state',
  'temporary-chat',
  'workspace-attachments',
  'rendering-extensions',
  'change-request-status',
  'claude-runtime',
  'local-file-preview',
  'local-harness',
  'browser-multi-tabs',
  'embedded-browser',
]

export const PLUGIN_SEGMENTS = [
  'plugin-marketplace-lifecycle',
  'plugin-lifecycle',
  'skill-mention-rendering',
  'sites-plugin-auto-install',
]
