import { existsSync } from 'node:fs'
import { resolve } from 'node:path'

// The cloud-device-vnc checkpoint is internal-only: its scenario module lives
// under wecode/, which the open-source checkout does not contain. Keep the
// checkpoint out of the catalog there so every consumer, including the CI
// classifier that validates its plan against this list, stays consistent.
const internalVncScenarioModule = '../../wecode/e2e/desktop/index.mjs'

export const VNC_DESKTOP_CHECKPOINT = existsSync(
  resolve(import.meta.dirname, internalVncScenarioModule)
)
  ? { name: 'cloud-device-vnc', scenarioModule: internalVncScenarioModule }
  : null

export const DESKTOP_CHECKPOINTS = [
  'remote-device-onboarding',
  'workspace-tabs',
  'cloud-project-creation',
  'cloud-device-lifecycle',
  ...(VNC_DESKTOP_CHECKPOINT ? [VNC_DESKTOP_CHECKPOINT.name] : []),
  'cloud-space-mention',
  'collaboration-shared-core',
  'collaboration-settings-matrix',
  'collaboration-first-use',
  'collaboration-local-agent-capabilities',
  'collaboration-agent-automation-chain',
  'priority-filter',
  'telemetry-consent',
  'external-content-import',
  'send-key-preference',
  'system-proxy',
  'system-pac',
  'workbench-mode',
  'automation-lifecycle',
  'project-automation',
  'project-event-sources',
  'project-assignment-notification',
  'offline-local-project-space',
  'board-focus-view',
  'cloud-context-resilience',
  'core-dsh-plugin-management',
  'plugin-development',
  'plugin-auto-update',
  'plugin-account-auth',
  'plugin-workspace-publication',
  'project-ai-settings',
  'model-routing',
  'fork-provider-preservation',
  'codex-account-login',
  'permission-modes',
  'computer-use',
  'task-status-sync',
  'task-board-association',
  'core-task-flow',
  'task-attachments',
  'cloud-git-worktree',
  'cloud-worktree-capability',
  'cloud-worktree-create',
  'cloud-worktree-queued-cancel',
  'cloud-worktree-tools',
  'cloud-worktree-archive-restore',
  'context-compaction',
  'runtime-task-queue',
  'executor-stream-recovery',
  'transcript-sync',
  'running-conversation-history',
  'running-plan-history',
  'codex-notification-isolation',
  'split-workbench',
  'release-package-startup',
  'app-update-differential',
  'app-update-baseline',
  'component-update',
  'native-window-startup',
  'native-window-chrome',
  'renderer-storage',
  'tray-lifecycle',
  'window-lifecycle',
  'goal-lifecycle',
  'supervisor-lifecycle',
  'resilience',
  'environment-panel-scroll',
  'conversation-state',
  'temporary-chat',
  'workspace-attachments',
  'rendering-extensions',
  'change-request-status',
  'claude-runtime',
  'local-file-preview',
  'local-harness',
  'harness-apps',
  'browser-multi-tabs',
  'embedded-browser',
  'browser-toolbar-actions',
  'browser-annotation',
  'browser-annotation-core',
  'browser-annotation-anchors',
  'browser-annotation-design',
  'dsh-owner-capture',
]

export const PLUGIN_SEGMENTS = [
  'core-dsh-ui-plugin-composition',
  'core-dsh-plugin-management',
  'plugin-marketplace-lifecycle',
  'plugin-lifecycle',
  'skill-mention-rendering',
  'sites-plugin-auto-install',
]
