# SPDX-FileCopyrightText: 2026 Weibo, Inc.
# SPDX-License-Identifier: Apache-2.0

"""Automatic external references for waiting workflow nodes.

A wait node declares the provider events it listens for. A stage directly
upstream of a wait node then carries an injected reference deliverable: the
system computes it from the wait node rules every time the stage requirements
are resolved, so editing a wait rule immediately changes what its upstream
stage must deliver. When the stage delivers the typed reference, the provider
adapter derives the opaque reference and the system registers the binding
automatically -- no prompt, tool call, or manual registration needed.

Everything provider-specific lives in the adapter registry; this module only
contains generic machinery.
"""

from __future__ import annotations

import logging
from typing import Any

from sqlalchemy.orm import Session

from app.models.delivery import (
    ExternalEventBinding,
    LoopItem,
    loop_datetime_is_unset,
)
from app.services.external_events.adapters import provider_reference_adapter
from app.services.external_events.binding import external_event_binding_service
from app.services.external_events.registration import (
    external_event_registration_service,
)

logger = logging.getLogger(__name__)

# Requirement ids generated by this module are namespaced so they can never
# collide with author-defined deliverables and are recognizable when a
# fulfillment references them.
INJECTED_REQUIREMENT_PREFIX = "__wait_ref__"


def injected_reference_requirements(
    workflow: dict[str, Any],
    node: dict[str, Any],
) -> list[dict[str, Any]]:
    """Reference deliverables a stage must produce for downstream wait nodes.

    One requirement per (wait node, provider): the provider adapter declares
    the fulfillment kind it accepts, so adding a provider is a data change in
    the adapter registry, not a new code path. Rules without a provider (custom
    events) never inject a requirement; those references stay manual.
    """

    node_id = str(node.get("id") or "")
    if not node_id:
        return []
    requirements: list[dict[str, Any]] = []
    for candidate in workflow.get("nodes") or []:
        if not isinstance(candidate, dict) or candidate.get("node_type") != "wait":
            continue
        wait_id = str(candidate.get("id") or "")
        if not wait_id or node_id not in (candidate.get("depends_on") or []):
            continue
        seen: set[str] = set()
        for rule in (candidate.get("wait_config") or {}).get("rules") or []:
            if not isinstance(rule, dict):
                continue
            provider = str(rule.get("provider") or "").strip()
            adapter = provider_reference_adapter(provider)
            if adapter is None or not adapter.reference_kind:
                continue
            if provider in seen:
                continue
            seen.add(provider)
            requirements.append(
                {
                    "id": f"{INJECTED_REQUIREMENT_PREFIX}{wait_id}_{provider}",
                    "name": f"{adapter.reference_name} 引用",
                    "description": adapter.reference_description,
                    "value_type": adapter.reference_kind,
                }
            )
    return requirements


def resolved_workflow_requirements(
    workflow: dict[str, Any],
    node: dict[str, Any],
) -> list[dict[str, Any]]:
    """A stage's own requirements plus its injected reference requirements."""

    authored = node.get("required_deliverables")
    authored = (
        [dict(value) for value in authored if isinstance(value, dict)]
        if isinstance(authored, list)
        else []
    )
    return [*authored, *injected_reference_requirements(workflow, node)]


def bind_references_from_delivery(
    db: Session,
    *,
    item: LoopItem,
    workflow: dict[str, Any],
    node: dict[str, Any],
    fulfillments: list[dict[str, Any]],
    automation_run_id: str,
    user_id: int,
) -> int:
    """Register bindings derived from one delivered reference.

    Returns how many bindings were registered. A malformed or undeliverable
    reference never fails the delivery itself: the failure is logged and
    recorded on the affected wait node as ``registration_error`` so a dead
    listener is visible on the card instead of living only in the logs.
    """

    wait_nodes = [
        candidate
        for candidate in workflow.get("nodes") or []
        if isinstance(candidate, dict)
        and candidate.get("node_type") == "wait"
        and str(node.get("id")) in (candidate.get("depends_on") or [])
    ]
    if not wait_nodes:
        return 0
    registered = 0
    errors: dict[str, list[str]] = {}
    for fulfillment in fulfillments:
        if not isinstance(fulfillment, dict):
            continue
        for provider in _fulfillment_providers(workflow, node, fulfillment):
            adapter = provider_reference_adapter(provider)
            if adapter is None:
                continue
            wait_node = _wait_node_for_provider(wait_nodes, provider)
            if wait_node is None:
                continue
            wait_id = str(wait_node.get("id") or "")
            opaque_refs = adapter.extract_opaque_refs(fulfillment)
            if not opaque_refs:
                errors.setdefault(wait_id, []).append(
                    "no reference derivable from delivered fulfillment"
                )
                continue
            for opaque_ref in opaque_refs:
                try:
                    external_event_registration_service.register(
                        db,
                        user_id=user_id,
                        cloud_project_id=str(item.cloud_project_id),
                        loop_item_id=item.id,
                        provider=provider,
                        opaque_ref=opaque_ref,
                        automation_run_id=automation_run_id,
                        workflow_node_id=str(wait_node.get("id")),
                    )
                    _archive_superseded_bindings(
                        db,
                        item_id=item.id,
                        workflow_node_id=str(wait_node.get("id")),
                        provider=provider,
                        keep_opaque_ref=opaque_ref,
                    )
                    registered += 1
                except Exception:
                    logger.exception(
                        "Automatic reference binding failed item=%s provider=%s ref=%s",
                        item.id,
                        provider,
                        opaque_ref,
                    )
                    errors.setdefault(wait_id, []).append(
                        f"registration failed for {opaque_ref}"
                    )
    _sync_registration_errors(db, item=item, wait_nodes=wait_nodes, errors=errors)
    return registered


def _sync_registration_errors(
    db: Session,
    *,
    item: LoopItem,
    wait_nodes: list[dict[str, Any]],
    errors: dict[str, list[str]],
) -> None:
    """Persist wait-node registration errors and clear fully-successful ones.

    The error is part of the node snapshot the API exposes, so the card can
    show why a listener is not receiving events. A later delivery that binds
    every expected reference clears the field again.
    """

    metadata = item.metadata_json if isinstance(item.metadata_json, dict) else {}
    workflow = metadata.get("workflow")
    raw_nodes = workflow.get("nodes") if isinstance(workflow, dict) else None
    if not isinstance(raw_nodes, list):
        return
    nodes = [dict(value) for value in raw_nodes if isinstance(value, dict)]
    changed = False
    for wait_node in wait_nodes:
        wait_id = str(wait_node.get("id") or "")
        error = "；".join(errors.get(wait_id) or [])
        for candidate in nodes:
            if candidate.get("id") != wait_id:
                continue
            if error and candidate.get("registration_error") != error:
                candidate["registration_error"] = error
                changed = True
            elif not error and candidate.get("registration_error"):
                candidate.pop("registration_error", None)
                changed = True
            break
    if changed:
        from app.services.project_workflow_projection import apply_workflow_nodes

        apply_workflow_nodes(item, workflow=workflow, nodes=nodes)
        # Registration commits its own transaction; the error snapshot is part
        # of that same side effect and must not wait for the caller's session.
        db.commit()


def _archive_superseded_bindings(
    db: Session,
    *,
    item_id: str,
    workflow_node_id: str,
    provider: str,
    keep_opaque_ref: str,
) -> None:
    """Retire earlier references of the same provider on the same wait node.

    A repair round that delivers a new MR replaces the previous one: its stale
    events (e.g. the old MR merging) must not complete the wait node. Bindings
    of other providers are untouched, so one wait node can keep listening to
    several providers at once.
    """

    rows = (
        db.query(ExternalEventBinding)
        .filter(
            ExternalEventBinding.loop_item_id == item_id,
            ExternalEventBinding.provider == provider,
            ExternalEventBinding.opaque_ref != keep_opaque_ref,
            ExternalEventBinding.metadata_json["workflow_node_id"].as_string()
            == workflow_node_id,
            loop_datetime_is_unset(ExternalEventBinding.deleted_at),
        )
        .all()
    )
    for row in rows:
        external_event_binding_service.archive(db, row)


def _fulfillment_providers(
    workflow: dict[str, Any],
    node: dict[str, Any],
    fulfillment: dict[str, Any],
) -> set[str]:
    """The providers a fulfillment may be a reference for.

    Typed references (e.g. ``pull_request``) carry their own provider; a
    provider-less fulfillment is accepted only when its requirement id matches
    an injected requirement of the node, so one fulfillment kind can serve
    several providers without ambiguity.
    """

    providers: set[str] = set()
    provider = str(fulfillment.get("provider") or "").strip()
    if provider:
        providers.add(provider)
    requirement_id = str(fulfillment.get("requirement_id") or "")
    if not requirement_id.startswith(INJECTED_REQUIREMENT_PREFIX):
        return providers
    node_id = str(node.get("id") or "")
    for candidate in workflow.get("nodes") or []:
        if (
            not isinstance(candidate, dict)
            or candidate.get("node_type") != "wait"
            or node_id not in (candidate.get("depends_on") or [])
        ):
            continue
        wait_id = str(candidate.get("id") or "")
        for rule in (candidate.get("wait_config") or {}).get("rules") or []:
            if not isinstance(rule, dict):
                continue
            rule_provider = str(rule.get("provider") or "").strip()
            if (
                rule_provider
                and requirement_id
                == f"{INJECTED_REQUIREMENT_PREFIX}{wait_id}_{rule_provider}"
            ):
                providers.add(rule_provider)
    return providers


def _wait_node_for_provider(
    wait_nodes: list[dict[str, Any]],
    provider: str,
) -> dict[str, Any] | None:
    for wait in wait_nodes:
        for rule in (wait.get("wait_config") or {}).get("rules") or []:
            if (
                isinstance(rule, dict)
                and str(rule.get("provider") or "").strip() == provider
            ):
                return wait
    return None
