// SPDX-FileCopyrightText: 2026 Weibo, Inc.
//
// SPDX-License-Identifier: Apache-2.0

import type { CollaborationLocale } from "../i18n";
import type { ProjectCreateLabels } from "./types";

export const projectCreateLabels: Record<
  CollaborationLocale,
  ProjectCreateLabels
> = {
  "zh-CN": {
    locale: "zh-CN",
    title: "新建项目",
    name: "名称",
    namePlaceholder: "例如：Wegent V4",
    location: "保存位置",
    locationImmutable: "创建后不可更改",
    localLocation: "本地空间",
    localLocationDescription: "保存在当前设备，可接入 GitHub 或 GitLab Issues",
    cloudLocation: "云端空间",
    cloudLocationDescription: "保存在 Wegent 云端，可在不同设备访问",
    visibility: "项目可见性",
    privateVisibility: "私有",
    privateVisibilityDescription: "仅项目成员可访问",
    publicVisibility: "公开",
    publicVisibilityDescription: "所有登录用户可访问",
    publicVisibilityNotice:
      "公开项目可被所有已登录用户查看，请勿放置敏感信息。",
    taskProvider: "任务来源",
    advancedSettings: "更多设置",
    builtInProvider: "内置任务",
    builtInLocalDescription: "保存在本机",
    builtInCloudDescription: "保存在云端",
    githubDescription: "读取 Issues",
    gitlabDescription: "读取 Issues",
    aitableProvider: "钉钉多维表格",
    aitableDescription: "同步表格记录",
    repository: "仓库地址",
    repositoryHint:
      "支持 HTTPS、SSH 或 owner/repository 格式；自托管地址会自动识别。",
    token: "访问令牌",
    optional: "可选",
    privateRepositoryToken: "私有仓库需要访问令牌",
    cloudTokenHint:
      "令牌会加密保存在 Wegent Backend，并安全下发给本地 Executor。",
    localTokenHint: "令牌会加密保存在当前设备，不会写入项目文件。",
    aitableUrl: "多维表格链接",
    aitablePlaceholder: "粘贴 alidocs.dingtalk.com 多维表格链接",
    aitableInvalid: "无法识别这个链接，请复制打开多维表格后的完整浏览器地址。",
    aitableHint: "将自动识别表格和当前数据表，无需查找内部 ID。",
    aitableRuntimeHint:
      "表格读写统一由本机 Executor 通过 DWS 执行。创建后连接钉钉账号，并确保该账号已获得此表格权限。",
    description: "说明",
    descriptionPlaceholder: "这个项目用于什么？",
    collaborators: "项目协作者",
    currentUser: "我",
    addCollaborator: "添加协作者",
    importGroupDescription: "使用已有分工创建项目专属小组",
    availableAgents: "已有智能体",
    availableGroups: "协作小组",
    noAvailableCollaborators: "暂无其他可添加项",
    groupRecommendationTitle: "建议组织成协作小组",
    groupRecommendationDescription:
      "多个智能体独立协作时需要你逐个分配任务。转为协作小组后，由一个负责人拆解、分派并汇总，负责人也可以直接执行工作。",
    keepDirectCollaboration: "保持独立协作",
    organizeAsGroup: "组织成协作小组",
    createCollaborationGroup: "新建协作小组",
    generatingGroup: "AI 正在生成分工…",
    groupDraftTitle: "AI 分工建议",
    groupName: "小组名称",
    groupLeader: "负责人",
    leaderWorks: "负责人 · 协调并执行",
    specialistWorks: "专项执行",
    setAsLeader: "设为负责人",
    generatedWorkflow: "建议流程",
    editResponsibilities: "编辑分工",
    supplementResponsibility: "点击补充职责",
    supplementAllocationPrinciples: "点击补充分配原则",
    removeGroup: "恢复独立协作",
    applyGroup: "保存分工",
    groupGenerationUnavailable: "请先选择新对话模型，再让 AI 生成分工",
    generationModel: "生成模型",
    generationModelLoading: "正在加载模型…",
    generationModelRequired: "请选择一个模型",
    selectGenerationModel: "组织协作小组",
    generationRequest: "分工要求",
    generationRequestPlaceholder:
      "补充你希望的协作方式、重点职责或交付要求（可选）",
    generationRequestDefault:
      "请结合项目目标和每个智能体的能力，生成清晰的职责分工、分配原则和执行流程。负责人需要参与实际工作。",
    selectedGenerationAgents: "参与分工的智能体",
    agentAttachment: "智能体",
    memberAttachment: "成员",
    standingInGroup: "已在小队，等待分工",
    generateResponsibilities: "生成分工",
    preparingGenerationModel: "正在准备模型",
    generatingResponsibilities: "AI 正在分析项目并生成分工",
    generationElapsed: "已等待 {{seconds}} 秒",
    waitingForAssignment: "AI 正在自动安排",
    automaticAssignmentHint: "AI 正在逐个生成职责，完成后会加入下方小组。",
    formingGroup: "协作小组",
    liveGeneration: "AI 实时生成",
    allocationPrinciples: "分配原则",
    generatingWorkflow: "正在形成执行流程…",
    groupSettingsHint: "保存后仍可在项目设置中更新成员职责和分配原则。",
    cancel: "取消",
    create: "创建项目",
    creating: "正在创建…",
    unavailableLocation: "所选项目位置当前不可用",
    repositoryRequired: "请输入仓库地址",
    repositoryInvalid: "请输入完整仓库地址，或使用 owner/repository 格式",
    githubRepositoryInvalid: "GitHub 仓库地址应包含 owner/repository",
    gitlabRepositoryInvalid: "GitLab 仓库地址应包含 group/project",
    createFailed: "创建项目失败",
  },
  en: {
    locale: "en",
    title: "New project",
    name: "Name",
    namePlaceholder: "For example: Wegent V4",
    location: "Storage location",
    locationImmutable: "Cannot be changed after creation",
    localLocation: "Local space",
    localLocationDescription:
      "Stored on this device; supports GitHub or GitLab Issues",
    cloudLocation: "Cloud space",
    cloudLocationDescription:
      "Stored in Wegent Cloud and available across devices",
    visibility: "Project visibility",
    privateVisibility: "Private",
    privateVisibilityDescription: "Project members only",
    publicVisibility: "Public",
    publicVisibilityDescription: "All signed-in users",
    publicVisibilityNotice:
      "All signed-in users can view this project. Avoid sensitive data.",
    taskProvider: "Task source",
    advancedSettings: "Advanced settings",
    builtInProvider: "Built-in tasks",
    builtInLocalDescription: "Stored locally",
    builtInCloudDescription: "Stored in the cloud",
    githubDescription: "Use Issues",
    gitlabDescription: "Use Issues",
    aitableProvider: "DingTalk AI Table",
    aitableDescription: "Synchronize table records",
    repository: "Repository",
    repositoryHint: "HTTPS, SSH, and owner/repository formats are supported.",
    token: "Access token",
    optional: "Optional",
    privateRepositoryToken: "Required for private repositories",
    cloudTokenHint:
      "The token is encrypted in Wegent Backend and securely sent to the executor.",
    localTokenHint:
      "The token is encrypted on this device and is not written to project files.",
    aitableUrl: "AI Table URL",
    aitablePlaceholder: "Paste an alidocs.dingtalk.com AI Table URL",
    aitableInvalid:
      "This URL could not be recognized. Copy the complete browser URL.",
    aitableHint: "The base and current table are detected automatically.",
    aitableRuntimeHint:
      "Table access runs through DWS on the local executor. Connect DingTalk after creation.",
    description: "Description",
    descriptionPlaceholder: "What is this project for?",
    collaborators: "Project collaborators",
    currentUser: "Me",
    addCollaborator: "Add collaborators",
    importGroupDescription: "Create a project group from this division of work",
    availableAgents: "Existing Agents",
    availableGroups: "Collaboration groups",
    noAvailableCollaborators: "Nothing else is available to add",
    groupRecommendationTitle: "Organize these Agents as a group",
    groupRecommendationDescription:
      "Independent Agents need separate task assignments. A group gives one working lead responsibility for delegation and synthesis.",
    keepDirectCollaboration: "Keep direct collaboration",
    organizeAsGroup: "Organize as a group",
    createCollaborationGroup: "Create collaboration group",
    generatingGroup: "AI is generating responsibilities…",
    groupDraftTitle: "AI responsibility draft",
    groupName: "Group name",
    groupLeader: "Lead",
    leaderWorks: "Lead · coordinates and executes",
    specialistWorks: "Specialist execution",
    setAsLeader: "Set as lead",
    generatedWorkflow: "Suggested workflow",
    editResponsibilities: "Edit responsibilities",
    supplementResponsibility: "Add a responsibility",
    supplementAllocationPrinciples: "Add allocation principles",
    removeGroup: "Return to direct collaboration",
    applyGroup: "Save division",
    groupGenerationUnavailable:
      "Select a model for new chats before asking AI to generate responsibilities",
    generationModel: "Generation model",
    generationModelLoading: "Loading models…",
    generationModelRequired: "Select a model",
    selectGenerationModel: "Organize a collaboration group",
    generationRequest: "Division requirements",
    generationRequestPlaceholder:
      "Add preferred collaboration, responsibility, or delivery requirements (optional)",
    generationRequestDefault:
      "Use the project goal and each agent's capabilities to generate clear responsibilities, allocation principles, and an execution workflow. The lead must also perform hands-on work.",
    selectedGenerationAgents: "Agents included in this division",
    agentAttachment: "Agent",
    memberAttachment: "Member",
    standingInGroup: "Already in the group, waiting for responsibilities",
    generateResponsibilities: "Generate responsibilities",
    preparingGenerationModel: "Preparing the model",
    generatingResponsibilities:
      "AI is analyzing the project and generating responsibilities",
    generationElapsed: "Waiting for {{seconds}} seconds",
    waitingForAssignment: "AI is arranging the group",
    automaticAssignmentHint:
      "AI is generating responsibilities one by one. Agents join the group after their responsibilities are ready.",
    formingGroup: "Collaboration group",
    liveGeneration: "AI live generation",
    allocationPrinciples: "Allocation principles",
    generatingWorkflow: "Building the execution workflow…",
    groupSettingsHint:
      "You can update responsibilities and allocation principles later in project settings.",
    cancel: "Cancel",
    create: "Create project",
    creating: "Creating…",
    unavailableLocation: "The selected project location is unavailable",
    repositoryRequired: "Enter a repository address",
    repositoryInvalid:
      "Enter a complete repository URL or use owner/repository",
    githubRepositoryInvalid:
      "A GitHub repository must include owner/repository",
    gitlabRepositoryInvalid: "A GitLab repository must include group/project",
    createFailed: "Failed to create project",
  },
};
