"""initial_schema

Revision ID: 020e34b70ee5
Revises:
Create Date: 2026-02-26 20:08:33.044599+08:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "020e34b70ee5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("trigger_type", sa.String(length=50), nullable=False),
        sa.Column("trigger_reason", sa.String(length=500), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("retry_attempt", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("background_executions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_background_executions_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_background_executions_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_background_executions_subscription_id"),
            ["subscription_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_background_executions_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_background_executions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            "ix_bg_exec_subscription_created",
            ["subscription_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_bg_exec_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_bg_exec_user_status", ["user_id", "status"], unique=False
        )

    op.create_table(
        "kinds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("namespace", sa.String(length=100), nullable=False),
        sa.Column("json", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("kinds", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_kinds_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_kinds_kind"), ["kind"], unique=False)

    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind_id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("file_extension", sa.String(length=50), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("enabled", "disabled", name="documentstatus"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("splitter_config", sa.JSON(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_config", sa.JSON(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("chunks", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Knowledge document table for file metadata",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("knowledge_documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_knowledge_documents_attachment", ["attachment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_id"), ["id"], unique=False
        )
        batch_op.create_index(
            "ix_knowledge_documents_kind_active_created",
            ["kind_id", "is_active", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_kind_id"), ["kind_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_documents_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "namespace",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="Group (Namespace) table for resource organization",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("namespace", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_namespace_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_namespace_level"), ["level"], unique=False)
        batch_op.create_index(batch_op.f("ix_namespace_name"), ["name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_namespace_owner_user_id"), ["owner_user_id"], unique=False
        )

    op.create_table(
        "namespace_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_name", "user_id", name="idx_group_user"),
        comment="Group membership table",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("namespace_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_namespace_members_group_name"), ["group_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_namespace_members_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_namespace_members_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False, comment="Primary key"),
        sa.Column(
            "user_id", sa.Integer(), nullable=False, comment="Project owner user ID"
        ),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Project name"
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Project description"
        ),
        sa.Column(
            "color",
            sa.String(length=20),
            nullable=True,
            comment="Project color identifier (e.g., #FF5733)",
        ),
        sa.Column(
            "sort_order", sa.Integer(), nullable=False, comment="Sort order for display"
        ),
        sa.Column(
            "is_expanded",
            sa.Boolean(),
            nullable=False,
            comment="Whether the project is expanded in UI",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the project is active (soft delete)",
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Creation timestamp"
        ),
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, comment="Last update timestamp"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Projects table for task organization",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_projects_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "share_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "resource_type",
            sa.String(length=50),
            nullable=False,
            comment="Resource type: Team, Task, KnowledgeBase",
        ),
        sa.Column(
            "resource_id",
            sa.Integer(),
            nullable=False,
            comment="Resource ID (kinds.id or tasks.id)",
        ),
        sa.Column(
            "share_token",
            sa.String(length=512),
            nullable=False,
            comment="AES encrypted share token",
        ),
        sa.Column(
            "require_approval",
            sa.Boolean(),
            nullable=False,
            comment="Whether joining requires approval",
        ),
        sa.Column(
            "default_permission_level",
            sa.String(length=20),
            server_default="view",
            nullable=False,
            comment="Default permission level: view, edit, manage",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            server_default="9999-12-31 23:59:59",
            nullable=False,
            comment="Expiration time (far future = never expires)",
        ),
        sa.Column(
            "created_by_user_id",
            sa.Integer(),
            nullable=False,
            comment="User who created the share link",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the link is active",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("share_token"),
        comment="Share link configurations for resources",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("share_links", schema=None) as batch_op:
        batch_op.create_index(
            "idx_share_links_active_resource",
            ["resource_type", "resource_id", "is_active"],
            unique=False,
        )
        batch_op.create_index(
            "idx_share_links_resource", ["resource_type", "resource_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_share_links_id"), ["id"], unique=False)

    op.create_table(
        "subscription_follows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("follower_user_id", sa.Integer(), nullable=False),
        sa.Column("follow_type", sa.String(length=20), nullable=False),
        sa.Column("invited_by_user_id", sa.Integer(), nullable=False),
        sa.Column("invitation_status", sa.String(length=20), nullable=False),
        sa.Column("invited_at", sa.DateTime(), nullable=False),
        sa.Column("responded_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("config", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subscription_follows", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sub_follow_follower", ["follower_user_id"], unique=False
        )
        batch_op.create_index(
            "ix_sub_follow_pending_invitations",
            ["follower_user_id", "invitation_status"],
            unique=False,
        )
        batch_op.create_index(
            "ix_sub_follow_subscription", ["subscription_id"], unique=False
        )
        batch_op.create_index(
            "ix_sub_follow_unique", ["subscription_id", "follower_user_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_follows_follower_user_id"),
            ["follower_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_follows_subscription_id"),
            ["subscription_id"],
            unique=False,
        )

    op.create_table(
        "subscription_share_namespaces",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("namespace_id", sa.Integer(), nullable=False),
        sa.Column("shared_by_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subscription_share_namespaces", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sub_share_ns_unique", ["subscription_id", "namespace_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_share_namespaces_namespace_id"),
            ["namespace_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_share_namespaces_subscription_id"),
            ["subscription_id"],
            unique=False,
        )

    op.create_table(
        "subtask_contexts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subtask_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("context_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column(
            "binary_data",
            sa.LargeBinary().with_variant(mysql.LONGBLOB(), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "image_base64",
            sa.Text().with_variant(mysql.LONGTEXT(), "mysql"),
            nullable=False,
        ),
        sa.Column(
            "extracted_text",
            sa.Text().with_variant(mysql.LONGTEXT(), "mysql"),
            nullable=False,
        ),
        sa.Column("text_length", sa.Integer(), nullable=False),
        sa.Column("type_data", mysql.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("subtask_contexts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subtask_contexts_context_type"),
            ["context_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subtask_contexts_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subtask_contexts_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subtask_contexts_subtask_id"), ["subtask_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_subtask_contexts_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "subtasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("bot_ids", sa.JSON(), nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "ASSISTANT", name="subtaskrole"), nullable=False
        ),
        sa.Column("executor_namespace", sa.String(length=100), nullable=True),
        sa.Column("executor_name", sa.String(length=100), nullable=True),
        sa.Column("executor_deleted_at", sa.Boolean(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "DELETE",
                "PENDING_CONFIRMATION",
                name="subtaskstatus",
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("sender_type", sa.String(length=20), nullable=False),
        sa.Column("sender_user_id", sa.Integer(), nullable=False),
        sa.Column("reply_to_subtask_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("subtasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subtasks_id"), ["id"], unique=False)

    op.create_table(
        "system_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_key", sa.String(length=100), nullable=False),
        sa.Column("config_value", sa.String(length=4096), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("system_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_system_configs_config_key"), ["config_key"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_system_configs_id"), ["id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False, comment="Primary key"),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="User ID, references users.id",
        ),
        sa.Column(
            "kind",
            sa.String(length=50),
            nullable=False,
            comment="Resource type: Task/Workspace",
        ),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Resource name"
        ),
        sa.Column(
            "namespace", sa.String(length=100), nullable=False, comment="Namespace"
        ),
        sa.Column(
            "json", sa.JSON(), nullable=False, comment="Resource-specific data (JSON)"
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Active flag"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Creation time"),
        sa.Column("updated_at", sa.DateTime(), nullable=False, comment="Update time"),
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=False,
            comment="Project ID for task grouping",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "kind", "name", "namespace", name="uniq_user_kind_name_namespace"
        ),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tasks_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tasks_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tasks_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tasks_user_id"), ["user_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("git_info", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("auth_source", sa.String(length=20), nullable=False),
        sa.Column("preferences", sa.String(length=4096), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_name"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)

    op.create_table(
        "wiki_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_name", sa.String(length=200), nullable=False),
        sa.Column("project_type", sa.String(length=50), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("source_domain", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ext", sa.JSON(), nullable=True, comment="Project extension data"),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_url"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("wiki_projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_wiki_projects_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_wiki_projects_project_name"), ["project_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_projects_project_type"), ["project_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_projects_source_type"), ["source_type"], unique=False
        )

    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(length=256), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_api_keys_key_type"), ["key_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "resource_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "resource_type",
            sa.String(length=50),
            nullable=False,
            comment="Resource type: Team, Task, KnowledgeBase",
        ),
        sa.Column("resource_id", sa.Integer(), nullable=False, comment="Resource ID"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="Member user ID"),
        sa.Column(
            "permission_level",
            sa.String(length=20),
            server_default="view",
            nullable=False,
            comment="Permission level: view, edit, manage",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
            comment="Status: pending, approved, rejected",
        ),
        sa.Column(
            "invited_by_user_id",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Inviter user ID (0 = via link or owner)",
        ),
        sa.Column(
            "share_link_id",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Associated share link ID (0 = not via link)",
        ),
        sa.Column(
            "reviewed_by_user_id",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Reviewer user ID (0 = not yet reviewed or auto-approved)",
        ),
        sa.Column(
            "reviewed_at",
            sa.DateTime(),
            server_default="1970-01-01 00:00:00",
            nullable=False,
            comment="Review timestamp (epoch = not reviewed)",
        ),
        sa.Column(
            "copied_resource_id",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Copied resource ID (0 = not copied, for Task copy behavior)",
        ),
        sa.Column(
            "requested_at", sa.DateTime(), nullable=False, comment="Request timestamp"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "resource_type", "resource_id", "user_id", name="uq_resource_members"
        ),
        comment="Resource member permissions and access control",
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("resource_members", schema=None) as batch_op:
        batch_op.create_index(
            "idx_resource_members_resource",
            ["resource_type", "resource_id"],
            unique=False,
        )
        batch_op.create_index(
            "idx_resource_members_resource_status",
            ["resource_type", "resource_id", "status"],
            unique=False,
        )
        batch_op.create_index("idx_resource_members_status", ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_resource_members_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_resource_members_share_link_id"),
            ["share_link_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_resource_members_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "skill_binaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind_id", sa.Integer(), nullable=False),
        sa.Column("binary_data", sa.LargeBinary(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["kind_id"], ["kinds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind_id"),
        mysql_charset="utf8mb4",
        mysql_collate="utf8mb4_unicode_ci",
        mysql_engine="InnoDB",
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("skill_binaries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skill_binaries_id"), ["id"], unique=False)

    op.create_table(
        "wiki_generations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column(
            "generation_type",
            sa.Enum("FULL", "INCREMENTAL", "CUSTOM", name="wikigenerationtype"),
            nullable=False,
        ),
        sa.Column(
            "source_snapshot",
            sa.JSON(),
            nullable=False,
            comment="Source snapshot information",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="wikigenerationstatus",
            ),
            nullable=False,
        ),
        sa.Column("ext", sa.JSON(), nullable=True, comment="Extension fields"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["wiki_projects.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("wiki_generations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_user_project", ["user_id", "project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_generations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_generations_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_generations_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_generations_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_generations_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_generations_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "wiki_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("generation_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("ext", sa.JSON(), nullable=True, comment="Content extension data"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["generation_id"], ["wiki_generations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    with op.batch_alter_table("wiki_contents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wiki_contents_generation_id"),
            ["generation_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_wiki_contents_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_wiki_contents_type"), ["type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wiki_contents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wiki_contents_type"))
        batch_op.drop_index(batch_op.f("ix_wiki_contents_id"))
        batch_op.drop_index(batch_op.f("ix_wiki_contents_generation_id"))

    op.drop_table("wiki_contents")
    with op.batch_alter_table("wiki_generations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wiki_generations_user_id"))
        batch_op.drop_index(batch_op.f("ix_wiki_generations_task_id"))
        batch_op.drop_index(batch_op.f("ix_wiki_generations_status"))
        batch_op.drop_index(batch_op.f("ix_wiki_generations_project_id"))
        batch_op.drop_index(batch_op.f("ix_wiki_generations_id"))
        batch_op.drop_index(batch_op.f("ix_wiki_generations_created_at"))
        batch_op.drop_index("idx_user_project")

    op.drop_table("wiki_generations")
    with op.batch_alter_table("skill_binaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_binaries_id"))

    op.drop_table("skill_binaries")
    with op.batch_alter_table("resource_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_resource_members_share_link_id"))
        batch_op.drop_index(batch_op.f("ix_resource_members_id"))
        batch_op.drop_index("idx_resource_members_status")
        batch_op.drop_index("idx_resource_members_resource_status")
        batch_op.drop_index("idx_resource_members_resource")

    op.drop_table("resource_members")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key_type"))
        batch_op.drop_index(batch_op.f("ix_api_keys_id"))

    op.drop_table("api_keys")
    with op.batch_alter_table("wiki_projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wiki_projects_source_type"))
        batch_op.drop_index(batch_op.f("ix_wiki_projects_project_type"))
        batch_op.drop_index(batch_op.f("ix_wiki_projects_project_name"))
        batch_op.drop_index(batch_op.f("ix_wiki_projects_id"))

    op.drop_table("wiki_projects")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_id"))

    op.drop_table("users")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_user_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_project_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_kind"))
        batch_op.drop_index(batch_op.f("ix_tasks_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_created_at"))

    op.drop_table("tasks")
    with op.batch_alter_table("system_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_system_configs_id"))
        batch_op.drop_index(batch_op.f("ix_system_configs_config_key"))

    op.drop_table("system_configs")
    with op.batch_alter_table("subtasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtasks_id"))

    op.drop_table("subtasks")
    with op.batch_alter_table("subtask_contexts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtask_contexts_user_id"))
        batch_op.drop_index(batch_op.f("ix_subtask_contexts_subtask_id"))
        batch_op.drop_index(batch_op.f("ix_subtask_contexts_status"))
        batch_op.drop_index(batch_op.f("ix_subtask_contexts_id"))
        batch_op.drop_index(batch_op.f("ix_subtask_contexts_context_type"))

    op.drop_table("subtask_contexts")
    with op.batch_alter_table("subscription_share_namespaces", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_subscription_share_namespaces_subscription_id")
        )
        batch_op.drop_index(batch_op.f("ix_subscription_share_namespaces_namespace_id"))
        batch_op.drop_index("ix_sub_share_ns_unique")

    op.drop_table("subscription_share_namespaces")
    with op.batch_alter_table("subscription_follows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscription_follows_subscription_id"))
        batch_op.drop_index(batch_op.f("ix_subscription_follows_follower_user_id"))
        batch_op.drop_index("ix_sub_follow_unique")
        batch_op.drop_index("ix_sub_follow_subscription")
        batch_op.drop_index("ix_sub_follow_pending_invitations")
        batch_op.drop_index("ix_sub_follow_follower")

    op.drop_table("subscription_follows")
    with op.batch_alter_table("share_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_share_links_id"))
        batch_op.drop_index("idx_share_links_resource")
        batch_op.drop_index("idx_share_links_active_resource")

    op.drop_table("share_links")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_user_id"))
        batch_op.drop_index(batch_op.f("ix_projects_id"))

    op.drop_table("projects")
    with op.batch_alter_table("namespace_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_namespace_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_namespace_members_id"))
        batch_op.drop_index(batch_op.f("ix_namespace_members_group_name"))

    op.drop_table("namespace_members")
    with op.batch_alter_table("namespace", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_namespace_owner_user_id"))
        batch_op.drop_index(batch_op.f("ix_namespace_name"))
        batch_op.drop_index(batch_op.f("ix_namespace_level"))
        batch_op.drop_index(batch_op.f("ix_namespace_id"))

    op.drop_table("namespace")
    with op.batch_alter_table("knowledge_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_user_id"))
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_kind_id"))
        batch_op.drop_index("ix_knowledge_documents_kind_active_created")
        batch_op.drop_index(batch_op.f("ix_knowledge_documents_id"))
        batch_op.drop_index("ix_knowledge_documents_attachment")

    op.drop_table("knowledge_documents")
    with op.batch_alter_table("kinds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kinds_kind"))
        batch_op.drop_index(batch_op.f("ix_kinds_id"))

    op.drop_table("kinds")
    with op.batch_alter_table("background_executions", schema=None) as batch_op:
        batch_op.drop_index("ix_bg_exec_user_status")
        batch_op.drop_index("ix_bg_exec_user_created")
        batch_op.drop_index("ix_bg_exec_subscription_created")
        batch_op.drop_index(batch_op.f("ix_background_executions_user_id"))
        batch_op.drop_index(batch_op.f("ix_background_executions_task_id"))
        batch_op.drop_index(batch_op.f("ix_background_executions_subscription_id"))
        batch_op.drop_index(batch_op.f("ix_background_executions_status"))
        batch_op.drop_index(batch_op.f("ix_background_executions_created_at"))

    op.drop_table("background_executions")
    # ### end Alembic commands ###
