"""add flow tables and projects tables

Revision ID: 9e5d981fde27
Revises: p6q7r8s9t0u1
Create Date: 2026-01-19 16:00:10.667509+08:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e5d981fde27"
down_revision: Union[str, Sequence[str], None] = "p6q7r8s9t0u1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Get database connection to check table existence
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    # Drop wiki_generations table and indexes if exists
    if "wiki_generations" in existing_tables:
        op.drop_index(op.f("idx_created_at"), table_name="wiki_generations")
        op.drop_index(op.f("idx_project_id"), table_name="wiki_generations")
        op.drop_index(op.f("idx_status"), table_name="wiki_generations")
        op.drop_index(op.f("idx_task_id"), table_name="wiki_generations")
        op.drop_index(op.f("idx_user_id"), table_name="wiki_generations")
        op.drop_index(op.f("idx_user_project"), table_name="wiki_generations")
        op.drop_table("wiki_generations")

    # Drop flow_executions table and indexes if exists
    if "flow_executions" in existing_tables:
        op.drop_index(op.f("ix_flow_exec_created_at"), table_name="flow_executions")
        op.drop_index(op.f("ix_flow_exec_flow_created"), table_name="flow_executions")
        op.drop_index(op.f("ix_flow_exec_flow_id"), table_name="flow_executions")
        op.drop_index(op.f("ix_flow_exec_status"), table_name="flow_executions")
        op.drop_index(op.f("ix_flow_exec_task_id"), table_name="flow_executions")
        op.drop_index(op.f("ix_flow_exec_user_created"), table_name="flow_executions")
        op.drop_index(op.f("ix_flow_exec_user_id"), table_name="flow_executions")
        op.drop_index(op.f("ix_flow_exec_user_status"), table_name="flow_executions")
        op.drop_table("flow_executions")

    # Drop wiki_contents table and indexes if exists
    if "wiki_contents" in existing_tables:
        op.drop_index(op.f("idx_generation_id"), table_name="wiki_contents")
        op.drop_index(op.f("idx_type"), table_name="wiki_contents")
        op.drop_table("wiki_contents")

    # Drop flows table if exists
    if "flows" in existing_tables:
        op.drop_table("flows")

    # Drop wiki_projects table and indexes if exists
    if "wiki_projects" in existing_tables:
        op.drop_index(op.f("idx_project_name"), table_name="wiki_projects")
        op.drop_index(op.f("idx_project_type"), table_name="wiki_projects")
        op.drop_index(op.f("idx_source_type"), table_name="wiki_projects")
        op.drop_index(op.f("uniq_source_url"), table_name="wiki_projects")
        op.drop_table("wiki_projects")
    op.alter_column(
        "api_keys",
        "id",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="Primary key",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "api_keys",
        "user_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="User ID who owns this API key",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "key_hash",
        existing_type=mysql.VARCHAR(length=256),
        server_default=None,
        comment=None,
        existing_comment="SHA256 hash of the API key",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "key_prefix",
        existing_type=mysql.VARCHAR(length=16),
        server_default=None,
        comment=None,
        existing_comment="Display prefix of the key (e.g., wg-abc123...)",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "name",
        existing_type=mysql.VARCHAR(length=100),
        server_default=None,
        comment=None,
        existing_comment="User-defined name for this API key",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "key_type",
        existing_type=mysql.VARCHAR(length=20),
        server_default=None,
        comment=None,
        existing_comment="Key type: personal or service",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "description",
        existing_type=mysql.VARCHAR(length=500),
        server_default=None,
        comment=None,
        existing_comment="Key description",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "expires_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="Expiration time, 9999-12-31 means never expires",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "last_used_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="Last time this key was used",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        comment=None,
        existing_comment="Whether the key is active (1=active, 0=deleted)",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="Creation timestamp",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="Last update timestamp",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_api_keys_id"), table_name="api_keys")
    op.drop_index(op.f("idx_api_keys_key_type"), table_name="api_keys")
    op.drop_index(op.f("idx_api_keys_user_id"), table_name="api_keys")
    op.create_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    op.create_index(
        op.f("ix_api_keys_key_type"), "api_keys", ["key_type"], unique=False
    )
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_foreign_key(None, "api_keys", "users", ["user_id"], ["id"])
    op.alter_column(
        "kinds",
        "namespace",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "kinds",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "kinds",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "kinds",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "knowledge_documents",
        "attachment_id",
        existing_type=mysql.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "file_size",
        existing_type=mysql.BIGINT(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "status",
        existing_type=mysql.ENUM("enabled", "disabled"),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "splitter_config",
        existing_type=mysql.JSON(),
        nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "source_type",
        existing_type=mysql.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "source_config",
        existing_type=mysql.JSON(),
        nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "summary",
        existing_type=mysql.JSON(),
        comment=None,
        existing_comment="Document summary information (JSON)",
        existing_nullable=True,
    )
    op.alter_column(
        "knowledge_documents",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_knowledge_documents_source_type"), table_name="knowledge_documents"
    )
    op.create_index(
        op.f("ix_knowledge_documents_id"), "knowledge_documents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_documents_kind_id"),
        "knowledge_documents",
        ["kind_id"],
        unique=False,
    )
    op.create_table_comment(
        "knowledge_documents",
        "Knowledge document table for file metadata",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "namespace",
        "id",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="Primary key ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "namespace",
        "name",
        existing_type=mysql.VARCHAR(length=100),
        server_default=None,
        comment=None,
        existing_comment="Unique identifier, immutable after creation. Sub-groups use prefix format (e.g., aaa/bbb)",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace",
        "display_name",
        existing_type=mysql.VARCHAR(length=100),
        server_default=None,
        nullable=True,
        comment=None,
        existing_comment="Display name, can be modified",
    )
    op.alter_column(
        "namespace",
        "owner_user_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="Group owner user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace",
        "visibility",
        existing_type=mysql.VARCHAR(length=20),
        server_default=None,
        comment=None,
        existing_comment="Visibility: private, internal, public",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace",
        "description",
        existing_type=mysql.TEXT(),
        comment=None,
        existing_comment="Group description",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        nullable=True,
        comment=None,
        existing_comment="Is group active",
    )
    op.alter_column(
        "namespace",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        nullable=True,
        comment=None,
        existing_comment="Creation timestamp",
    )
    op.alter_column(
        "namespace",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        nullable=True,
        comment=None,
        existing_comment="Last update timestamp",
    )
    op.drop_index(op.f("idx_namespace_owner_user_id"), table_name="namespace")
    op.drop_index(op.f("uniq_namespace_name"), table_name="namespace")
    op.create_index(op.f("ix_namespace_id"), "namespace", ["id"], unique=False)
    op.create_index(op.f("ix_namespace_name"), "namespace", ["name"], unique=True)
    op.create_index(
        op.f("ix_namespace_owner_user_id"), "namespace", ["owner_user_id"], unique=False
    )
    op.alter_column(
        "namespace_members",
        "id",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="Primary key ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "namespace_members",
        "group_name",
        existing_type=mysql.VARCHAR(length=100),
        server_default=None,
        comment=None,
        existing_comment="References namespace.name",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace_members",
        "user_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="Member user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace_members",
        "role",
        existing_type=mysql.VARCHAR(length=20),
        server_default=None,
        comment=None,
        existing_comment="Member role: Owner, Maintainer, Developer, Reporter",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace_members",
        "invited_by_user_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="User ID who invited this member",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace_members",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        nullable=True,
        comment=None,
        existing_comment="Is membership active",
    )
    op.alter_column(
        "namespace_members",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        nullable=True,
        comment=None,
        existing_comment="Membership creation timestamp",
    )
    op.alter_column(
        "namespace_members",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        nullable=True,
        comment=None,
        existing_comment="Last update timestamp",
    )
    op.drop_index(op.f("idx_namespace_members_user_id"), table_name="namespace_members")
    op.drop_index(op.f("uniq_group_user"), table_name="namespace_members")
    op.create_unique_constraint(
        "idx_group_user", "namespace_members", ["group_name", "user_id"]
    )
    op.create_index(
        op.f("ix_namespace_members_group_name"),
        "namespace_members",
        ["group_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_namespace_members_id"), "namespace_members", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_namespace_members_user_id"),
        "namespace_members",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "shared_tasks",
        "id",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="主键ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "shared_tasks",
        "user_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="当前用户ID",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "original_user_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="原始任务所有者用户ID",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "original_task_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="原始任务ID",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "copied_task_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        nullable=True,
        comment=None,
        existing_comment="复制后的任务ID",
    )
    op.alter_column(
        "shared_tasks",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        comment=None,
        existing_comment="是否激活",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="更新时间",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_shared_tasks_copied_task_id"), table_name="shared_tasks")
    op.drop_index(op.f("idx_shared_tasks_id"), table_name="shared_tasks")
    op.drop_index(op.f("idx_shared_tasks_original_task_id"), table_name="shared_tasks")
    op.drop_index(op.f("idx_shared_tasks_original_user_id"), table_name="shared_tasks")
    op.drop_index(op.f("idx_shared_tasks_user_id"), table_name="shared_tasks")
    op.drop_index(op.f("uniq_user_original_task"), table_name="shared_tasks")
    op.create_index(
        op.f("ix_shared_tasks_copied_task_id"),
        "shared_tasks",
        ["copied_task_id"],
        unique=False,
    )
    op.create_index(op.f("ix_shared_tasks_id"), "shared_tasks", ["id"], unique=False)
    op.create_index(
        op.f("ix_shared_tasks_original_task_id"),
        "shared_tasks",
        ["original_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shared_tasks_original_user_id"),
        "shared_tasks",
        ["original_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shared_tasks_user_id"), "shared_tasks", ["user_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_user_original_task", "shared_tasks", ["user_id", "original_task_id"]
    )
    op.create_foreign_key(
        None, "shared_tasks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "shared_tasks", "users", ["original_user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "shared_tasks", "kinds", ["copied_task_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "shared_tasks", "kinds", ["original_task_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "shared_teams",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "shared_teams",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "shared_teams",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "skill_binaries",
        "binary_data",
        existing_type=mysql.LONGBLOB(),
        type_=sa.LargeBinary(),
        existing_nullable=False,
    )
    op.alter_column(
        "skill_binaries",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "subtask_contexts",
        "subtask_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "status",
        existing_type=mysql.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtask_contexts", "error_message", existing_type=mysql.TEXT(), nullable=False
    )
    op.alter_column(
        "subtask_contexts",
        "binary_data",
        existing_type=mysql.LONGBLOB(),
        nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "image_base64",
        existing_type=mysql.LONGTEXT(),
        nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "extracted_text",
        existing_type=mysql.LONGTEXT(),
        nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "text_length",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_index(
        op.f("idx_subtask_contexts_subtask_id"), table_name="subtask_contexts"
    )
    op.drop_index(op.f("idx_subtask_contexts_user_id"), table_name="subtask_contexts")
    op.create_index(
        op.f("ix_subtask_contexts_context_type"),
        "subtask_contexts",
        ["context_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subtask_contexts_id"), "subtask_contexts", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_subtask_contexts_status"), "subtask_contexts", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_subtask_contexts_subtask_id"),
        "subtask_contexts",
        ["subtask_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subtask_contexts_user_id"),
        "subtask_contexts",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "subtasks",
        "role",
        existing_type=mysql.ENUM("USER", "ASSISTANT", collation="utf8mb4_unicode_ci"),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "executor_deleted_at",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "message_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "status",
        existing_type=mysql.ENUM(
            "PENDING",
            "RUNNING",
            "COMPLETED",
            "FAILED",
            "CANCELLED",
            "DELETE",
            collation="utf8mb4_unicode_ci",
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "progress",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "subtasks",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "subtasks", "completed_at", existing_type=mysql.DATETIME(), nullable=False
    )
    op.alter_column(
        "subtasks",
        "sender_type",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        server_default=None,
        comment=None,
        existing_comment="Sender type: USER or TEAM, empty string for non-group-chat messages",
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "sender_user_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="User ID when sender_type=USER, 0 for non-user senders",
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "reply_to_subtask_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="Quoted message ID for reply feature, 0 for no reply",
        existing_nullable=False,
    )
    op.alter_column(
        "system_configs",
        "config_value",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=4096),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "system_configs",
        "version",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "system_configs",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "system_configs",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.drop_index(op.f("config_key"), table_name="system_configs")
    op.drop_index(op.f("ix_system_configs_config_key"), table_name="system_configs")
    op.create_index(
        op.f("ix_system_configs_config_key"),
        "system_configs",
        ["config_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_system_configs_id"), "system_configs", ["id"], unique=False
    )
    op.alter_column(
        "task_members",
        "id",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="Primary key",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "task_members",
        "task_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="Related Task Kind.id",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "user_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="Member user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "invited_by",
        existing_type=mysql.INTEGER(),
        server_default=None,
        comment=None,
        existing_comment="Inviter user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "status",
        existing_type=mysql.VARCHAR(length=20),
        server_default=None,
        comment=None,
        existing_comment="Member status: ACTIVE or REMOVED",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "joined_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="Join timestamp",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "removed_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="Removal timestamp, default epoch time for not removed",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="Creation timestamp",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        comment=None,
        existing_comment="Last update timestamp",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_task_members_task_id"), table_name="task_members")
    op.drop_index(op.f("idx_task_members_user_id"), table_name="task_members")
    op.create_index(op.f("ix_task_members_id"), "task_members", ["id"], unique=False)
    op.create_index(
        op.f("ix_task_members_task_id"), "task_members", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_members_user_id"), "task_members", ["user_id"], unique=False
    )
    op.alter_column(
        "tasks",
        "id",
        existing_type=mysql.INTEGER(),
        comment="Primary key",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "tasks",
        "user_id",
        existing_type=mysql.INTEGER(),
        comment="User ID, references users.id",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "kind",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
        comment="Resource type: Task/Workspace",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "name",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        comment="Resource name",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "namespace",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        server_default=None,
        comment="Namespace",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "json",
        existing_type=mysql.JSON(),
        comment="Resource-specific data (JSON)",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        nullable=False,
        comment="Active flag",
    )
    op.alter_column(
        "tasks",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        nullable=False,
        comment="Creation time",
    )
    op.alter_column(
        "tasks",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        nullable=False,
        comment="Update time",
    )
    op.alter_column(
        "tasks",
        "project_id",
        existing_type=mysql.INTEGER(),
        server_default=None,
        existing_comment="Project ID for task grouping",
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_kinds_id"), table_name="tasks")
    op.drop_index(op.f("ix_kinds_kind"), table_name="tasks")
    op.create_index(op.f("ix_tasks_created_at"), "tasks", ["created_at"], unique=False)
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("ix_tasks_kind"), "tasks", ["kind"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uniq_user_kind_name_namespace",
        "tasks",
        ["user_id", "kind", "name", "namespace"],
    )
    op.drop_column("tasks", "canvas_updated_at")
    op.drop_column("tasks", "canvas_content")
    op.drop_column("tasks", "canvas_enabled")
    op.drop_column("tasks", "canvas_title")
    op.drop_column("tasks", "canvas_file_type")
    op.alter_column(
        "users",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "auth_source",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "preferences",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=4096),
        server_default=None,
        comment=None,
        existing_comment="user preferences",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=None,
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "preferences",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=4096),
        server_default=sa.text("'{}'"),
        comment="user preferences",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "auth_source",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        server_default=sa.text("'unknown'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        server_default=sa.text("'user'"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=True,
    )
    op.add_column(
        "tasks",
        sa.Column(
            "canvas_file_type",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
            server_default=sa.text("'text'"),
            nullable=True,
            comment="Canvas file type",
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "canvas_title",
            mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=255),
            server_default=sa.text("'Untitled'"),
            nullable=True,
            comment="Canvas title",
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "canvas_enabled",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="Whether canvas mode is enabled",
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "canvas_content",
            mysql.TEXT(collation="utf8mb4_unicode_ci"),
            nullable=True,
            comment="Canvas content",
        ),
    )
    op.add_column(
        "tasks",
        sa.Column(
            "canvas_updated_at",
            mysql.DATETIME(),
            nullable=True,
            comment="Last canvas update time",
        ),
    )
    op.drop_constraint("uniq_user_kind_name_namespace", "tasks", type_="unique")
    op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_kind"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_at"), table_name="tasks")
    op.create_index(op.f("ix_kinds_kind"), "tasks", ["kind"], unique=False)
    op.create_index(op.f("ix_kinds_id"), "tasks", ["id"], unique=False)
    op.create_index(op.f("idx_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.alter_column(
        "tasks",
        "project_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        existing_comment="Project ID for task grouping",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        nullable=True,
        comment=None,
        existing_comment="Update time",
    )
    op.alter_column(
        "tasks",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        nullable=True,
        comment=None,
        existing_comment="Creation time",
    )
    op.alter_column(
        "tasks",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        nullable=True,
        comment=None,
        existing_comment="Active flag",
    )
    op.alter_column(
        "tasks",
        "json",
        existing_type=mysql.JSON(),
        comment=None,
        existing_comment="Resource-specific data (JSON)",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "namespace",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        server_default=sa.text("'default'"),
        comment=None,
        existing_comment="Namespace",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "name",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        comment=None,
        existing_comment="Resource name",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "kind",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=50),
        comment=None,
        existing_comment="Resource type: Task/Workspace",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "user_id",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="User ID, references users.id",
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "id",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="Primary key",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_task_members_user_id"), table_name="task_members")
    op.drop_index(op.f("ix_task_members_task_id"), table_name="task_members")
    op.drop_index(op.f("ix_task_members_id"), table_name="task_members")
    op.create_index(
        op.f("idx_task_members_user_id"), "task_members", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_task_members_task_id"), "task_members", ["task_id"], unique=False
    )
    op.alter_column(
        "task_members",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        comment="Last update timestamp",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        comment="Creation timestamp",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "removed_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("'1970-01-01 00:00:00'"),
        comment="Removal timestamp, default epoch time for not removed",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "joined_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        comment="Join timestamp",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "status",
        existing_type=mysql.VARCHAR(length=20),
        server_default=sa.text("'ACTIVE'"),
        comment="Member status: ACTIVE or REMOVED",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "invited_by",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="Inviter user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "user_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="Member user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "task_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="Related Task Kind.id",
        existing_nullable=False,
    )
    op.alter_column(
        "task_members",
        "id",
        existing_type=mysql.INTEGER(),
        comment="Primary key",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_system_configs_id"), table_name="system_configs")
    op.drop_index(op.f("ix_system_configs_config_key"), table_name="system_configs")
    op.create_index(
        op.f("ix_system_configs_config_key"),
        "system_configs",
        ["config_key"],
        unique=False,
    )
    op.create_index(op.f("config_key"), "system_configs", ["config_key"], unique=True)
    op.alter_column(
        "system_configs",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=True,
    )
    op.alter_column(
        "system_configs",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=True,
    )
    op.alter_column(
        "system_configs",
        "version",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "system_configs",
        "config_value",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=4096),
        server_default=sa.text("'{}'"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "reply_to_subtask_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="Quoted message ID for reply feature, 0 for no reply",
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "sender_user_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="User ID when sender_type=USER, 0 for non-user senders",
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "sender_type",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=20),
        server_default=sa.text("''"),
        comment="Sender type: USER or TEAM, empty string for non-group-chat messages",
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks", "completed_at", existing_type=mysql.DATETIME(), nullable=True
    )
    op.alter_column(
        "subtasks",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "subtasks",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "subtasks",
        "progress",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "status",
        existing_type=mysql.ENUM(
            "PENDING",
            "RUNNING",
            "COMPLETED",
            "FAILED",
            "CANCELLED",
            "DELETE",
            collation="utf8mb4_unicode_ci",
        ),
        server_default=sa.text("'PENDING'"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "message_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "executor_deleted_at",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtasks",
        "role",
        existing_type=mysql.ENUM("USER", "ASSISTANT", collation="utf8mb4_unicode_ci"),
        server_default=sa.text("'ASSISTANT'"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_subtask_contexts_user_id"), table_name="subtask_contexts")
    op.drop_index(op.f("ix_subtask_contexts_subtask_id"), table_name="subtask_contexts")
    op.drop_index(op.f("ix_subtask_contexts_status"), table_name="subtask_contexts")
    op.drop_index(op.f("ix_subtask_contexts_id"), table_name="subtask_contexts")
    op.drop_index(
        op.f("ix_subtask_contexts_context_type"), table_name="subtask_contexts"
    )
    op.create_index(
        op.f("idx_subtask_contexts_user_id"),
        "subtask_contexts",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_subtask_contexts_subtask_id"),
        "subtask_contexts",
        ["subtask_id"],
        unique=False,
    )
    op.alter_column(
        "subtask_contexts",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "text_length",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "extracted_text",
        existing_type=mysql.LONGTEXT(),
        nullable=True,
    )
    op.alter_column(
        "subtask_contexts",
        "image_base64",
        existing_type=mysql.LONGTEXT(),
        nullable=True,
    )
    op.alter_column(
        "subtask_contexts", "binary_data", existing_type=mysql.LONGBLOB(), nullable=True
    )
    op.alter_column(
        "subtask_contexts", "error_message", existing_type=mysql.TEXT(), nullable=True
    )
    op.alter_column(
        "subtask_contexts",
        "status",
        existing_type=mysql.VARCHAR(length=20),
        server_default=sa.text("'pending'"),
        existing_nullable=False,
    )
    op.alter_column(
        "subtask_contexts",
        "subtask_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "skill_binaries",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "skill_binaries",
        "binary_data",
        existing_type=sa.LargeBinary(),
        type_=mysql.LONGBLOB(),
        existing_nullable=False,
    )
    op.alter_column(
        "shared_teams",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "shared_teams",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "shared_teams",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=True,
    )
    op.drop_constraint(None, "shared_tasks", type_="foreignkey")
    op.drop_constraint(None, "shared_tasks", type_="foreignkey")
    op.drop_constraint(None, "shared_tasks", type_="foreignkey")
    op.drop_constraint(None, "shared_tasks", type_="foreignkey")
    op.drop_constraint("uq_user_original_task", "shared_tasks", type_="unique")
    op.drop_index(op.f("ix_shared_tasks_user_id"), table_name="shared_tasks")
    op.drop_index(op.f("ix_shared_tasks_original_user_id"), table_name="shared_tasks")
    op.drop_index(op.f("ix_shared_tasks_original_task_id"), table_name="shared_tasks")
    op.drop_index(op.f("ix_shared_tasks_id"), table_name="shared_tasks")
    op.drop_index(op.f("ix_shared_tasks_copied_task_id"), table_name="shared_tasks")
    op.create_index(
        op.f("uniq_user_original_task"),
        "shared_tasks",
        ["user_id", "original_task_id"],
        unique=True,
    )
    op.create_index(
        op.f("idx_shared_tasks_user_id"), "shared_tasks", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_shared_tasks_original_user_id"),
        "shared_tasks",
        ["original_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_shared_tasks_original_task_id"),
        "shared_tasks",
        ["original_task_id"],
        unique=False,
    )
    op.create_index(op.f("idx_shared_tasks_id"), "shared_tasks", ["id"], unique=False)
    op.create_index(
        op.f("idx_shared_tasks_copied_task_id"),
        "shared_tasks",
        ["copied_task_id"],
        unique=False,
    )
    op.alter_column(
        "shared_tasks",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        comment="更新时间",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        comment="创建时间",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        comment="是否激活",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "copied_task_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        nullable=False,
        comment="复制后的任务ID",
    )
    op.alter_column(
        "shared_tasks",
        "original_task_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="原始任务ID",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "original_user_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="原始任务所有者用户ID",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "user_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="当前用户ID",
        existing_nullable=False,
    )
    op.alter_column(
        "shared_tasks",
        "id",
        existing_type=mysql.INTEGER(),
        comment="主键ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_namespace_members_user_id"), table_name="namespace_members")
    op.drop_index(op.f("ix_namespace_members_id"), table_name="namespace_members")
    op.drop_index(
        op.f("ix_namespace_members_group_name"), table_name="namespace_members"
    )
    op.drop_constraint("idx_group_user", "namespace_members", type_="unique")
    op.create_index(
        op.f("uniq_group_user"),
        "namespace_members",
        ["group_name", "user_id"],
        unique=True,
    )
    op.create_index(
        op.f("idx_namespace_members_user_id"),
        "namespace_members",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "namespace_members",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        nullable=False,
        comment="Last update timestamp",
    )
    op.alter_column(
        "namespace_members",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        nullable=False,
        comment="Membership creation timestamp",
    )
    op.alter_column(
        "namespace_members",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        nullable=False,
        comment="Is membership active",
    )
    op.alter_column(
        "namespace_members",
        "invited_by_user_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="User ID who invited this member",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace_members",
        "role",
        existing_type=mysql.VARCHAR(length=20),
        server_default=sa.text("''"),
        comment="Member role: Owner, Maintainer, Developer, Reporter",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace_members",
        "user_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="Member user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace_members",
        "group_name",
        existing_type=mysql.VARCHAR(length=100),
        server_default=sa.text("''"),
        comment="References namespace.name",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace_members",
        "id",
        existing_type=mysql.INTEGER(),
        comment="Primary key ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index(op.f("ix_namespace_owner_user_id"), table_name="namespace")
    op.drop_index(op.f("ix_namespace_name"), table_name="namespace")
    op.drop_index(op.f("ix_namespace_id"), table_name="namespace")
    op.create_index(op.f("uniq_namespace_name"), "namespace", ["name"], unique=True)
    op.create_index(
        op.f("idx_namespace_owner_user_id"),
        "namespace",
        ["owner_user_id"],
        unique=False,
    )
    op.alter_column(
        "namespace",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        nullable=False,
        comment="Last update timestamp",
    )
    op.alter_column(
        "namespace",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        nullable=False,
        comment="Creation timestamp",
    )
    op.alter_column(
        "namespace",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        nullable=False,
        comment="Is group active",
    )
    op.alter_column(
        "namespace",
        "description",
        existing_type=mysql.TEXT(),
        comment="Group description",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace",
        "visibility",
        existing_type=mysql.VARCHAR(length=20),
        server_default=sa.text("'private'"),
        comment="Visibility: private, internal, public",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace",
        "owner_user_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="Group owner user ID",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace",
        "display_name",
        existing_type=mysql.VARCHAR(length=100),
        server_default=sa.text("''"),
        nullable=False,
        comment="Display name, can be modified",
    )
    op.alter_column(
        "namespace",
        "name",
        existing_type=mysql.VARCHAR(length=100),
        server_default=sa.text("''"),
        comment="Unique identifier, immutable after creation. Sub-groups use prefix format (e.g., aaa/bbb)",
        existing_nullable=False,
    )
    op.alter_column(
        "namespace",
        "id",
        existing_type=mysql.INTEGER(),
        comment="Primary key ID",
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_table_comment(
        "knowledge_documents",
        existing_comment="Knowledge document table for file metadata",
        schema=None,
    )
    op.drop_index(
        op.f("ix_knowledge_documents_kind_id"), table_name="knowledge_documents"
    )
    op.drop_index(op.f("ix_knowledge_documents_id"), table_name="knowledge_documents")
    op.create_index(
        op.f("ix_knowledge_documents_source_type"),
        "knowledge_documents",
        ["source_type"],
        unique=False,
    )
    op.alter_column(
        "knowledge_documents",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "summary",
        existing_type=mysql.JSON(),
        comment="Document summary information (JSON)",
        existing_nullable=True,
    )
    op.alter_column(
        "knowledge_documents",
        "source_config",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "knowledge_documents",
        "source_type",
        existing_type=mysql.VARCHAR(length=50),
        server_default=sa.text("'file'"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "splitter_config",
        existing_type=mysql.JSON(),
        nullable=True,
    )
    op.alter_column(
        "knowledge_documents",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "status",
        existing_type=mysql.ENUM("enabled", "disabled"),
        server_default=sa.text("'enabled'"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "file_size",
        existing_type=mysql.BIGINT(),
        server_default=sa.text("'0'"),
        existing_nullable=False,
    )
    op.alter_column(
        "knowledge_documents",
        "attachment_id",
        existing_type=mysql.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "kinds",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "kinds",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=True,
    )
    op.alter_column(
        "kinds",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        existing_nullable=True,
    )
    op.alter_column(
        "kinds",
        "namespace",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=100),
        server_default=sa.text("'default'"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_type"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_id"), table_name="api_keys")
    op.create_index(op.f("idx_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_api_keys_key_type"), "api_keys", ["key_type"], unique=False
    )
    op.create_index(op.f("idx_api_keys_id"), "api_keys", ["id"], unique=False)
    op.alter_column(
        "api_keys",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        comment="Last update timestamp",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "created_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        comment="Creation timestamp",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "is_active",
        existing_type=mysql.TINYINT(display_width=1),
        server_default=sa.text("'1'"),
        comment="Whether the key is active (1=active, 0=deleted)",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "last_used_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        comment="Last time this key was used",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "expires_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("'9999-12-31 23:59:59'"),
        comment="Expiration time, 9999-12-31 means never expires",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "description",
        existing_type=mysql.VARCHAR(length=500),
        server_default=sa.text("''"),
        comment="Key description",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "key_type",
        existing_type=mysql.VARCHAR(length=20),
        server_default=sa.text("'personal'"),
        comment="Key type: personal or service",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "name",
        existing_type=mysql.VARCHAR(length=100),
        server_default=sa.text("''"),
        comment="User-defined name for this API key",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "key_prefix",
        existing_type=mysql.VARCHAR(length=16),
        server_default=sa.text("''"),
        comment="Display prefix of the key (e.g., wg-abc123...)",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "key_hash",
        existing_type=mysql.VARCHAR(length=256),
        server_default=sa.text("''"),
        comment="SHA256 hash of the API key",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "user_id",
        existing_type=mysql.INTEGER(),
        server_default=sa.text("'0'"),
        comment="User ID who owns this API key",
        existing_nullable=False,
    )
    op.alter_column(
        "api_keys",
        "id",
        existing_type=mysql.INTEGER(),
        comment="Primary key",
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table(
        "wiki_projects",
        sa.Column(
            "id",
            mysql.INTEGER(),
            autoincrement=True,
            nullable=False,
            comment="Primary key auto increment ID",
        ),
        sa.Column(
            "project_name",
            mysql.VARCHAR(length=200),
            server_default=sa.text("''"),
            nullable=False,
            comment="Project name",
        ),
        sa.Column(
            "project_type",
            mysql.VARCHAR(length=50),
            server_default=sa.text("'git'"),
            nullable=False,
            comment="Project type: git, local, etc",
        ),
        sa.Column(
            "source_type",
            mysql.VARCHAR(length=50),
            server_default=sa.text("'github'"),
            nullable=False,
            comment="Source type: github, gitlab, gitee, etc",
        ),
        sa.Column(
            "source_url",
            mysql.VARCHAR(length=500),
            server_default=sa.text("''"),
            nullable=False,
            comment="Source repository URL",
        ),
        sa.Column(
            "source_id",
            mysql.VARCHAR(length=100),
            server_default=sa.text("''"),
            nullable=False,
            comment="Source repository ID",
        ),
        sa.Column(
            "source_domain",
            mysql.VARCHAR(length=100),
            server_default=sa.text("''"),
            nullable=False,
            comment="Source domain name",
        ),
        sa.Column(
            "description", mysql.TEXT(), nullable=False, comment="Project description"
        ),
        sa.Column(
            "ext", mysql.JSON(), nullable=False, comment="Project extension data"
        ),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
            comment="Whether the project is active: 1=active, 0=inactive",
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Record creation time",
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Record update time",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("uniq_source_url"), "wiki_projects", ["source_url"], unique=True
    )
    op.create_index(
        op.f("idx_source_type"), "wiki_projects", ["source_type"], unique=False
    )
    op.create_index(
        op.f("idx_project_type"), "wiki_projects", ["project_type"], unique=False
    )
    op.create_index(
        op.f("idx_project_name"), "wiki_projects", ["project_name"], unique=False
    )
    op.create_table(
        "flows",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "kind",
            mysql.VARCHAR(length=50),
            server_default=sa.text("'Flow'"),
            nullable=False,
        ),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "namespace",
            mysql.VARCHAR(length=255),
            server_default=sa.text("'default'"),
            nullable=False,
        ),
        sa.Column("json", mysql.JSON(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "enabled",
            mysql.TINYINT(display_width=1),
            server_default=sa.text("'1'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("trigger_type", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("team_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("workspace_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("webhook_token", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("last_execution_time", mysql.DATETIME(), nullable=True),
        sa.Column("last_execution_status", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("next_execution_time", mysql.DATETIME(), nullable=True),
        sa.Column(
            "execution_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "success_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "failure_count",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column("webhook_secret", mysql.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "wiki_contents",
        sa.Column(
            "id",
            mysql.INTEGER(),
            autoincrement=True,
            nullable=False,
            comment="Primary key auto increment ID",
        ),
        sa.Column(
            "generation_id",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="Associated generation ID",
        ),
        sa.Column(
            "type",
            mysql.VARCHAR(length=50),
            server_default=sa.text("'chapter'"),
            nullable=False,
            comment="Content type: chapter, section, overview, etc",
        ),
        sa.Column(
            "title",
            mysql.VARCHAR(length=500),
            server_default=sa.text("''"),
            nullable=False,
            comment="Content title",
        ),
        sa.Column(
            "content",
            mysql.LONGTEXT(),
            nullable=False,
            comment="Content body in markdown format",
        ),
        sa.Column(
            "parent_id",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="Parent content ID for hierarchical structure",
        ),
        sa.Column(
            "ext", mysql.JSON(), nullable=False, comment="Content extension data"
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Record creation time",
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Record update time",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("idx_type"), "wiki_contents", ["type"], unique=False)
    op.create_index(
        op.f("idx_generation_id"), "wiki_contents", ["generation_id"], unique=False
    )
    op.create_table(
        "flow_executions",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("flow_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("task_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("trigger_type", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("trigger_reason", mysql.VARCHAR(length=500), nullable=True),
        sa.Column("prompt", mysql.TEXT(), nullable=False),
        sa.Column(
            "status",
            mysql.VARCHAR(length=50),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column("result_summary", mysql.TEXT(), nullable=True),
        sa.Column("error_message", mysql.TEXT(), nullable=True),
        sa.Column(
            "retry_attempt",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("started_at", mysql.DATETIME(), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(), nullable=True),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("(now())"),
            nullable=False,
        ),
        sa.Column(
            "version",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flow_id"],
            ["flows.id"],
            name=op.f("flow_executions_ibfk_1"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("ix_flow_exec_user_status"),
        "flow_executions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_exec_user_id"), "flow_executions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_flow_exec_user_created"),
        "flow_executions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_exec_task_id"), "flow_executions", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_flow_exec_status"), "flow_executions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_flow_exec_flow_id"), "flow_executions", ["flow_id"], unique=False
    )
    op.create_index(
        op.f("ix_flow_exec_flow_created"),
        "flow_executions",
        ["flow_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flow_exec_created_at"), "flow_executions", ["created_at"], unique=False
    )
    op.create_table(
        "wiki_generations",
        sa.Column(
            "id",
            mysql.INTEGER(),
            autoincrement=True,
            nullable=False,
            comment="Primary key auto increment ID",
        ),
        sa.Column(
            "project_id",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="Associated project ID",
        ),
        sa.Column(
            "user_id",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="User ID who created the generation",
        ),
        sa.Column(
            "task_id",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="Associated task ID",
        ),
        sa.Column(
            "team_id",
            mysql.INTEGER(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=False,
            comment="Team ID for task execution",
        ),
        sa.Column(
            "generation_type",
            mysql.VARCHAR(length=20),
            server_default=sa.text("'full'"),
            nullable=False,
            comment="Generation type: full, incremental, custom",
        ),
        sa.Column(
            "source_snapshot",
            mysql.JSON(),
            nullable=False,
            comment="Source snapshot information including branch, commit, etc",
        ),
        sa.Column(
            "status",
            mysql.VARCHAR(length=20),
            server_default=sa.text("'PENDING'"),
            nullable=False,
            comment="Generation status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED",
        ),
        sa.Column(
            "ext",
            mysql.JSON(),
            nullable=False,
            comment="Extension fields for additional metadata",
        ),
        sa.Column(
            "created_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Record creation time",
        ),
        sa.Column(
            "updated_at",
            mysql.DATETIME(),
            server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Record update time",
        ),
        sa.Column(
            "completed_at",
            mysql.DATETIME(),
            server_default=sa.text("'1970-01-01 00:00:00'"),
            nullable=False,
            comment="Generation completion time",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("idx_user_project"),
        "wiki_generations",
        ["user_id", "project_id"],
        unique=False,
    )
    op.create_index(op.f("idx_user_id"), "wiki_generations", ["user_id"], unique=False)
    op.create_index(op.f("idx_task_id"), "wiki_generations", ["task_id"], unique=False)
    op.create_index(op.f("idx_status"), "wiki_generations", ["status"], unique=False)
    op.create_index(
        op.f("idx_project_id"), "wiki_generations", ["project_id"], unique=False
    )
    op.create_index(
        op.f("idx_created_at"), "wiki_generations", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
