# SPDX-FileCopyrightText: 2025 Weibo, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""Transition page item model."""

from datetime import datetime

from sqlalchemy import JSON, BigInteger, Column, DateTime, Index, Integer, String, text

from app.db.base import Base


class TransitionPageItem(Base):
    """A typed configuration item belonging to one transition page."""

    __tablename__ = "transition_page_items"

    id = Column(BigInteger, primary_key=True, comment="Primary key ID, generated by Snowflake algorithm")
    page_id = Column(String(64), nullable=False, default="", server_default="", comment="Transition page ID")
    type = Column(String(32), nullable=False, default="", server_default="", comment="Item type")
    key = Column(String(128), nullable=False, default="", server_default="", comment="Item key within page/type")
    global_key = Column(
        String(191),
        nullable=False,
        default="",
        server_default="",
        comment="Optional globally unique lookup key",
    )
    parent_key = Column(String(128), nullable=False, default="", server_default="", comment="Optional parent item key")
    data_json = Column(JSON, nullable=False, default=dict, comment="JSON data")
    sort_order = Column(Integer, nullable=False, default=0, server_default="0", comment="Sort order")
    created_by = Column(Integer, nullable=False, server_default="0", comment="Created by user ID")
    updated_by = Column(Integer, nullable=False, server_default="0", comment="Updated by user ID")
    created_at = Column(DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP"), comment="Created at")
    updated_at = Column(
        DateTime,
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=datetime.now,
        comment="Updated at",
    )

    __table_args__ = (
        Index("uniq_transition_page_item", "page_id", "type", "key", unique=True),
        Index(
            "uniq_transition_page_items_global_key",
            "global_key",
            unique=True,
        ),
        Index("idx_transition_page_items_type_key", "type", "key"),
        Index("idx_transition_page_items_page_type", "page_id", "type"),
        Index(
            "idx_transition_page_items_page_type_order",
            "page_id",
            "type",
            "sort_order",
        ),
    )
