#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Weibo, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""Generate metric_spec.py from query.py's 9 legacy metric dicts.

One-shot codegen for the A1 refactor (collapse the 9 parallel dicts into a
single _METRIC_SPECS registry). Run from the knowledge_engine directory so
that `import knowledge_engine.stat.query` resolves:

    cd knowledge_engine && .venv/bin/python ../scripts/gen_metric_specs.py

Output overwrites knowledge_engine/knowledge_engine/stat/metric_spec.py.
After running, validate with scripts/verify_metric_specs.py.
"""

import pathlib
import textwrap

import knowledge_engine.stat.query as q

# These constants live in metric_spec.py (the canonical source). Importing
# them from there to regenerate the same file is a chicken-and-egg escape:
# we only read them for emitting the same literal, we don't recompute them.
from knowledge_engine.stat.metric_spec import (  # noqa: E402
    _KB_DETAIL_DOMAINS,
    _KB_DETAIL_EXCLUDED_METRICS,
)

# SCHEMAS is the list_metrics basis (what the API actually exposes). Note the
# legacy dicts have already drifted: DESCRIPTION omits daily_dashboard/
# period_totals, QUERY_OPTIONS omits global_totals/daily_dashboard/period_totals,
# and period_and_daily is a merged collector name (not a queryable metric) that
# exists only in DESCRIPTION/LABELS. We use SCHEMAS as the single source of
# truth and apply .get() fallbacks matching list_metrics' behavior.
NAMES = list(q._METRIC_SCHEMAS.keys())


def fmt_set(s):
    items = sorted(s)
    if not items:
        return "set()"
    return "{\n" + "".join(f"    {x!r},\n" for x in items) + "}"


def fmt_dict(d):
    if not d:
        return "{}"
    return "{\n" + "".join(f"    {k!r}: {v!r},\n" for k, v in d.items()) + "}"


def fmt_schema(cols):
    if not cols:
        return "()"
    inner = ", ".join(
        f"ColumnSpec(key={c['key']!r}, type={c['type']!r}, label={c['label']!r})"
        for c in cols
    )
    return f"({inner},)" if len(cols) == 1 else f"({inner})"


def fmt_query_options(name):
    qo = q._METRIC_QUERY_OPTIONS.get(name)
    if not qo:
        return "None"
    parts = []
    if qo.get("order_by") is not None:
        parts.append(f"order_by={qo['order_by']!r}")
    if qo.get("limit") is not None:
        parts.append(f"limit={qo['limit']}")
    return f"QueryOptions({', '.join(parts)})" if parts else "None"


def fmt_spec(name):
    return (
        f"    {name!r}: MetricSpec(\n"
        f"        name={name!r},\n"
        f"        table={q._METRIC_TABLES.get(name)!r},\n"
        f"        schema={fmt_schema(q._METRIC_SCHEMAS[name])},\n"
        f"        domain={q._METRIC_DOMAIN.get(name, 'other')!r},\n"
        f"        label={q._METRIC_LABELS.get(name, name)!r},\n"
        f"        description={q._METRIC_DESCRIPTION.get(name, '')!r},\n"
        f"        chart_hint={q._METRIC_CHART_HINT.get(name, 'table')!r},\n"
        f"        date_col={q._METRIC_DATE_COL.get(name)!r},\n"
        f"        kb_col={q._METRIC_KB_COL.get(name)!r},\n"
        f"        query_options={fmt_query_options(name)},\n"
        f"    ),"
    )


specs_block = "\n".join(fmt_spec(n) for n in NAMES)

chunks = []
chunks.append(
    textwrap.dedent(
        """\
        # SPDX-FileCopyrightText: 2026 Weibo, Inc.
        #
        # SPDX-License-Identifier: Apache-2.0

        \"\"\"Single source of truth for KB-stat metric metadata.

        Generated by scripts/gen_metric_specs.py from query.py's legacy 9-dict
        layout. Do not edit the _METRIC_SPECS literal by hand - regenerate it,
        then validate with scripts/verify_metric_specs.py.

        Phase 2 TODO: merge CollectorMeta (registry.py) domain/chart_hint/
        description into MetricSpec so each collector carries its own query
        metadata and the two structures stop drifting.
        \"\"\"

        from __future__ import annotations

        from dataclasses import dataclass
        from typing import Optional


        @dataclass(frozen=True, slots=True)
        class ColumnSpec:
            \"\"\"One column of a metric schema; serializes to {key, type, label}.\"\"\"

            key: str
            type: str  # date | int | float | string | datetime
            label: str


        @dataclass(frozen=True, slots=True)
        class QueryOptions:
            \"\"\"Optional ORDER BY / LIMIT for a metric query (sparse).\"\"\"

            order_by: Optional[str] = None
            limit: Optional[int] = None


        @dataclass(frozen=True, slots=True)
        class MetricSpec:
            \"\"\"All metadata for one metric, collapsed from the legacy 9 dicts.\"\"\"

            name: str
            table: str
            schema: tuple[ColumnSpec, ...]
            domain: str
            label: str
            description: str
            chart_hint: str = "table"
            date_col: Optional[str] = None  # None = cross-section snapshot
            kb_col: Optional[str] = None  # None = global metric
            query_options: Optional[QueryOptions] = None

        """
    )
)

chunks.append("# Domain display labels (moved from query.py).\n")
chunks.append("_DOMAIN_LABELS: dict[str, str] = " + fmt_dict(q._DOMAIN_LABELS) + "\n\n")
chunks.append(
    "# Domains visible in KB detail scope (merged from query.py + registry.py).\n"
)
chunks.append("_KB_DETAIL_DOMAINS: set[str] = " + fmt_set(_KB_DETAIL_DOMAINS) + "\n\n")
chunks.append("# Metrics without kb_id that should not appear on KB detail page.\n")
chunks.append(
    "_KB_DETAIL_EXCLUDED_METRICS: set[str] = "
    + fmt_set(_KB_DETAIL_EXCLUDED_METRICS)
    + "\n\n\n"
)

# NOTE: build_metric_list is intentionally NOT generated here. It is a
# runtime function that lives in query.py so that re-running this codegen
# can never silently drop fields (like date_col) from the metadata
# builder. metric_spec.py keeps a thin re-export shim for backward
# compatibility with existing imports.

chunks.append("# Metric specifications (generated - do not edit by hand).\n")
chunks.append("_METRIC_SPECS: dict[str, MetricSpec] = {\n")
chunks.append(specs_block + "\n")
chunks.append("}\n")

# Append a backward-compat shim for build_metric_list. The canonical
# implementation lives in query.py (runtime code); this shim lets existing
# `from metric_spec import build_metric_list` imports keep working after
# codegen regenerates this file.
chunks.append(
    textwrap.dedent(
        """\


    def build_metric_list(scope: str = "admin") -> list[dict]:
        \"\"\"Re-export shim — see knowledge_engine.stat.query.build_metric_list.\"\"\"
        from knowledge_engine.stat.query import build_metric_list as _impl

        return _impl(scope=scope)
    """
    )
)

content = "".join(chunks)

out = (
    pathlib.Path(__file__).resolve().parent.parent
    / "knowledge_engine"
    / "knowledge_engine"
    / "stat"
    / "metric_spec.py"
)
out.write_text(content, encoding="utf-8")
print(f"wrote {out} ({len(NAMES)} specs, {len(content)} bytes)")
