// SPDX-FileCopyrightText: 2025 Weibo, Inc.
//
// SPDX-License-Identifier: Apache-2.0

/**
 * Artifact API client for sandbox-generated files.
 *
 * Handles download and retrieval of files generated by sandbox tools
 * (e.g., PPT, DOCX, XLSX files created by document skills).
 */

import { getToken } from './user'

// API base URL - use relative path for browser compatibility
const API_BASE_URL = ''

/**
 * Artifact response from API
 */
export interface ArtifactResponse {
  id: number
  filename: string
  file_size: number
  mime_type: string
  status: string
  file_extension: string
  file_path?: string | null
  sandbox_id?: string | null
  created_at?: string | null
}

/**
 * Artifact list response
 */
export interface ArtifactListResponse {
  artifacts: ArtifactResponse[]
  total: number
}

/**
 * Get artifact details by ID
 *
 * @param artifactId - Artifact ID
 * @returns Artifact details
 */
export async function getArtifact(artifactId: number): Promise<ArtifactResponse> {
  const token = getToken()

  const response = await fetch(`${API_BASE_URL}/api/artifacts/${artifactId}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      ...(token && { Authorization: `Bearer ${token}` }),
    },
  })

  if (!response.ok) {
    const error = await response.json().catch(() => ({}))
    throw new Error(error.detail || 'Failed to get artifact')
  }

  return response.json()
}

/**
 * Get artifact download URL
 *
 * @param artifactId - Artifact ID
 * @returns Download URL
 */
export function getArtifactDownloadUrl(artifactId: number): string {
  return `${API_BASE_URL}/api/artifacts/${artifactId}/download`
}

/**
 * Download artifact file
 *
 * @param artifactId - Artifact ID
 * @param filename - Filename for download
 */
export async function downloadArtifact(artifactId: number, filename: string): Promise<void> {
  const token = getToken()

  const response = await fetch(`${API_BASE_URL}/api/artifacts/${artifactId}/download`, {
    method: 'GET',
    headers: {
      ...(token && { Authorization: `Bearer ${token}` }),
    },
  })

  if (!response.ok) {
    throw new Error('Failed to download artifact')
  }

  const blob = await response.blob()
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Get artifacts by subtask ID
 *
 * @param subtaskId - Subtask ID
 * @returns List of artifacts for the subtask
 */
export async function getArtifactsBySubtask(subtaskId: number): Promise<ArtifactListResponse> {
  const token = getToken()

  const response = await fetch(`${API_BASE_URL}/api/artifacts/subtask/${subtaskId}`, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      ...(token && { Authorization: `Bearer ${token}` }),
    },
  })

  if (!response.ok) {
    const error = await response.json().catch(() => ({}))
    throw new Error(error.detail || 'Failed to get artifacts')
  }

  return response.json()
}

/**
 * Delete an artifact
 *
 * @param artifactId - Artifact ID
 */
export async function deleteArtifact(artifactId: number): Promise<void> {
  const token = getToken()

  const response = await fetch(`${API_BASE_URL}/api/artifacts/${artifactId}`, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json',
      ...(token && { Authorization: `Bearer ${token}` }),
    },
  })

  if (!response.ok) {
    const error = await response.json().catch(() => ({}))
    throw new Error(error.detail || 'Failed to delete artifact')
  }
}

/**
 * Format file size for display
 */
export function formatFileSize(bytes: number): string {
  if (bytes < 1024) {
    return `${bytes} B`
  } else if (bytes < 1024 * 1024) {
    return `${(bytes / 1024).toFixed(1)} KB`
  } else {
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
  }
}

/**
 * Get file icon based on extension
 */
export function getArtifactFileIcon(extension: string): string {
  const ext = extension.toLowerCase()
  switch (ext) {
    case '.pdf':
      return '📄'
    case '.doc':
    case '.docx':
      return '📝'
    case '.ppt':
    case '.pptx':
      return '📊'
    case '.xls':
    case '.xlsx':
    case '.csv':
      return '📈'
    case '.png':
    case '.jpg':
    case '.jpeg':
    case '.gif':
    case '.svg':
      return '🖼️'
    case '.html':
      return '🌐'
    case '.json':
    case '.xml':
      return '📋'
    case '.zip':
    case '.tar':
    case '.gz':
      return '📦'
    default:
      return '📄'
  }
}

/**
 * Artifact API exports
 */
export const artifactApis = {
  getArtifact,
  getArtifactDownloadUrl,
  downloadArtifact,
  getArtifactsBySubtask,
  deleteArtifact,
}
