# SPDX-FileCopyrightText: 2026 Weibo, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""Metric column schemas, extracted from query.py (P2-5 split)."""

_METRIC_SCHEMAS: dict[str, list[dict]] = {
    # kb_lifecycle
    "kb_creation_trend": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "namespace", "type": "string", "label": "命名空间"},
        {"key": "new_kb_count", "type": "int", "label": "新增数量"},
        {"key": "cumulative_kb_count", "type": "int", "label": "累计数量"},
    ],
    "kb_activity": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_namespace", "type": "string", "label": "命名空间"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "document_count", "type": "int", "label": "文档数"},
        {"key": "last_doc_uploaded_at", "type": "datetime", "label": "最后上传"},
        {"key": "last_query_at", "type": "datetime", "label": "最后查询"},
        {"key": "is_stale", "type": "int", "label": "沉寂"},
        {"key": "is_inactive", "type": "int", "label": "不活跃"},
    ],
    "kb_topic_distribution": [
        {"key": "topic", "type": "string", "label": "主题"},
        {"key": "kb_count", "type": "int", "label": "知识库数"},
    ],
    "kb_retrieval_config": [
        {"key": "retrieval_mode", "type": "string", "label": "检索模式"},
        {"key": "top_k", "type": "int", "label": "返回数量"},
        {"key": "score_threshold", "type": "float", "label": "相似度阈值"},
        {"key": "kb_count", "type": "int", "label": "知识库数"},
    ],
    "kb_size_distribution": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "namespace", "type": "string", "label": "命名空间"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
        {"key": "total_file_size", "type": "int", "label": "总大小"},
        {"key": "avg_file_size", "type": "int", "label": "平均大小"},
        {"key": "max_file_size", "type": "int", "label": "最大大小"},
        {"key": "size_bucket", "type": "string", "label": "规模区间"},
    ],
    "kb_abandon_rate": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "namespace", "type": "string", "label": "命名空间"},
        {"key": "total_kb_count", "type": "int", "label": "总知识库数"},
        {"key": "stale_kb_count", "type": "int", "label": "沉寂数"},
        {"key": "inactive_kb_count", "type": "int", "label": "不活跃数"},
        {"key": "abandon_rate", "type": "float", "label": "废弃率 %"},
    ],
    "kb_sharing": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "member_count", "type": "int", "label": "成员数"},
        {"key": "share_link_count", "type": "int", "label": "分享链接数"},
        {"key": "owner_count", "type": "int", "label": "拥有者"},
        {"key": "maintainer_count", "type": "int", "label": "维护者"},
        {"key": "developer_count", "type": "int", "label": "开发者"},
        {"key": "reporter_count", "type": "int", "label": "报告者"},
        {"key": "restricted_analyst_count", "type": "int", "label": "受限分析师"},
    ],
    # dashboard
    "global_totals": [
        {"key": "total_kb_count", "type": "int", "label": "总知识库数"},
        {"key": "total_doc_count", "type": "int", "label": "总文档数"},
        {"key": "dingtalk_synced_user_count", "type": "int", "label": "钉钉同步用户"},
        {"key": "dingtalk_kb_count", "type": "int", "label": "钉钉知识库数"},
        {"key": "dingtalk_doc_count", "type": "int", "label": "钉钉文档数"},
    ],
    "period_totals": [
        {"key": "start_date", "type": "date", "label": "起始日期"},
        {"key": "end_date", "type": "date", "label": "结束日期"},
        {"key": "period_total_queries", "type": "int", "label": "总查询量"},
        {"key": "period_new_kb", "type": "int", "label": "新增知识库"},
        {"key": "period_new_docs", "type": "int", "label": "新增文档"},
        {"key": "period_rag_queries", "type": "int", "label": "RAG查询"},
        {"key": "period_direct_inject", "type": "int", "label": "直接注入"},
        {"key": "period_kb_head_queries", "type": "int", "label": "指定文档查询"},
    ],
    "daily_dashboard": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "total_queries", "type": "int", "label": "总查询量"},
        {"key": "rag_queries", "type": "int", "label": "RAG查询"},
        {"key": "direct_injection", "type": "int", "label": "直接注入"},
        {"key": "kb_head_rag_queries", "type": "int", "label": "指定文档RAG"},
        {"key": "kb_head_queries", "type": "int", "label": "指定文档"},
        {"key": "active_kb_count", "type": "int", "label": "活跃知识库"},
        {"key": "active_user_count", "type": "int", "label": "活跃用户"},
        {"key": "new_kb_count", "type": "int", "label": "新增知识库"},
        {"key": "new_doc_count", "type": "int", "label": "新增文档"},
        {"key": "dingtalk_active_user_count", "type": "int", "label": "钉钉活跃用户"},
    ],
    # doc_management
    "doc_upload_trend": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "source_type", "type": "string", "label": "来源"},
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "upload_count", "type": "int", "label": "上传数量"},
    ],
    "doc_index_status": [
        {"key": "index_status", "type": "string", "label": "索引状态"},
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    "doc_index_failure_rate": [
        {"key": "target_date", "type": "date", "label": "日期"},
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "total_count", "type": "int", "label": "总数"},
        {"key": "failed_count", "type": "int", "label": "失败数"},
        {"key": "failure_rate", "type": "float", "label": "失败率 %"},
    ],
    "doc_size_distribution": [
        {"key": "size_bucket", "type": "string", "label": "大小区间"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
        {"key": "total_size", "type": "int", "label": "总大小"},
    ],
    "doc_update_frequency": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "index_generation", "type": "int", "label": "索引代数"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    "doc_topic_distribution": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "topic", "type": "string", "label": "主题"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    "doc_folder_depth": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "depth", "type": "int", "label": "深度"},
        {"key": "folder_count", "type": "int", "label": "文件夹数"},
    ],
    "doc_chunk_strategy": [
        {"key": "splitter_type", "type": "string", "label": "分块器类型"},
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    "doc_chunk_count_distribution": [
        {"key": "chunk_bucket", "type": "string", "label": "分块数区间"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    "doc_summary_status": [
        {"key": "summary_status", "type": "string", "label": "摘要状态"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    # retrieval
    "rag_call_frequency": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "call_count", "type": "int", "label": "调用次数"},
    ],
    "kb_head_frequency": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "call_count", "type": "int", "label": "调用次数"},
    ],
    "rag_vs_head_ratio": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "rag_count", "type": "int", "label": "RAG次数"},
        {"key": "head_count", "type": "int", "label": "指定文档次数"},
        {"key": "rag_ratio", "type": "float", "label": "RAG占比 %"},
    ],
    "doc_reference_count": [
        {"key": "document_id", "type": "int", "label": "文档ID"},
        {"key": "document_name", "type": "string", "label": "文档名称"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "rag_ref_count", "type": "int", "label": "RAG引用"},
        {"key": "head_ref_count", "type": "int", "label": "指定文档引用"},
        {"key": "total_ref_count", "type": "int", "label": "总引用"},
    ],
    "doc_read_count": [
        {"key": "document_id", "type": "int", "label": "文档ID"},
        {"key": "document_name", "type": "string", "label": "文档名称"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "read_count", "type": "int", "label": "阅读次数"},
    ],
    "retrieval_mode_distribution": [
        {"key": "injection_mode", "type": "string", "label": "注入模式"},
        {"key": "call_count", "type": "int", "label": "调用次数"},
    ],
    "restricted_mode_usage": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_calls", "type": "int", "label": "总调用"},
        {"key": "restricted_calls", "type": "int", "label": "受限调用"},
        {"key": "restricted_rate", "type": "float", "label": "受限率 %"},
    ],
    "rag_call_limit": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "max_calls_config", "type": "int", "label": "调用上限"},
        {"key": "hit_limit_count", "type": "int", "label": "命中上限次数"},
    ],
    "selected_documents_usage": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "document_id", "type": "int", "label": "文档ID"},
        {"key": "select_count", "type": "int", "label": "指定次数"},
    ],
    "chunks_count_distribution": [
        {"key": "chunk_bucket", "type": "string", "label": "分块数区间"},
        {"key": "call_count", "type": "int", "label": "调用次数"},
    ],
    # user_behavior
    "kb_creator_ranking": [
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "kb_count", "type": "int", "label": "创建数"},
    ],
    "doc_uploader_ranking": [
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "upload_count", "type": "int", "label": "上传数"},
    ],
    "retrieval_active_user": [
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "rag_count", "type": "int", "label": "RAG次数"},
        {"key": "head_count", "type": "int", "label": "指定文档次数"},
        {"key": "total_count", "type": "int", "label": "总次数"},
        {"key": "user_tier", "type": "string", "label": "活跃等级"},
    ],
    "user_rag_head_preference": [
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "rag_count", "type": "int", "label": "RAG次数"},
        {"key": "head_count", "type": "int", "label": "指定文档次数"},
        {"key": "preference", "type": "string", "label": "偏好类型"},
    ],
    "user_kb_binding": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "task_count", "type": "int", "label": "任务数"},
    ],
    "user_permission_distribution": [
        {"key": "role", "type": "string", "label": "角色"},
        {"key": "user_count", "type": "int", "label": "用户数"},
    ],
    "restricted_analyst_usage": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "analyst_count", "type": "int", "label": "分析师数"},
    ],
    "user_first_kb_usage": [
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "registered_at", "type": "datetime", "label": "注册时间"},
        {"key": "first_kb_usage_at", "type": "datetime", "label": "首次使用时间"},
        {"key": "days_to_first", "type": "float", "label": "间隔天数"},
    ],
    "user_participation_summary": [
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "is_creator", "type": "int", "label": "创建者"},
        {"key": "is_uploader", "type": "int", "label": "上传者"},
        {"key": "is_retriever", "type": "int", "label": "检索者"},
        {"key": "is_member", "type": "int", "label": "成员"},
        {"key": "participation_type", "type": "string", "label": "参与类型"},
    ],
    # collaboration
    "kb_member_scale": [
        {"key": "scale_bucket", "type": "string", "label": "规模"},
        {"key": "kb_count", "type": "int", "label": "知识库数"},
    ],
    "invitation_chain": [
        {"key": "inviter_id", "type": "int", "label": "邀请人ID"},
        {"key": "inviter_name", "type": "string", "label": "邀请人"},
        {"key": "invitee_id", "type": "int", "label": "被邀请人ID"},
        {"key": "invitee_name", "type": "string", "label": "被邀请人"},
        {"key": "role", "type": "string", "label": "角色"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
    ],
    "share_link_usage": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "link_count", "type": "int", "label": "链接数"},
        {"key": "total_joins", "type": "int", "label": "总加入数"},
        {"key": "avg_joins_per_link", "type": "float", "label": "平均加入/链接"},
    ],
    "approval_efficiency": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "avg_approval_minutes", "type": "float", "label": "平均审批时长(分)"},
        {"key": "total_requests", "type": "int", "label": "总请求数"},
        {"key": "approved_count", "type": "int", "label": "批准数"},
        {"key": "approval_rate", "type": "float", "label": "批准率 %"},
    ],
    "cross_org_access": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_namespace", "type": "string", "label": "知识库命名空间"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_namespace", "type": "string", "label": "用户命名空间"},
        {"key": "role", "type": "string", "label": "角色"},
    ],
    "permission_change_trend": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "role", "type": "string", "label": "角色"},
        {"key": "status", "type": "string", "label": "状态"},
        {"key": "change_count", "type": "int", "label": "变更次数"},
    ],
    # sys_ops
    "storage_usage": [
        {"key": "target_date", "type": "date", "label": "日期"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "namespace", "type": "string", "label": "命名空间"},
        {"key": "total_file_size", "type": "int", "label": "总大小"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    "attachment_storage": [
        {"key": "storage_backend", "type": "string", "label": "存储后端"},
        {"key": "file_count", "type": "int", "label": "文件数"},
        {"key": "total_size", "type": "int", "label": "总大小"},
    ],
    "doc_index_storage_view": [
        {"key": "index_status", "type": "string", "label": "索引状态"},
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
        {"key": "total_file_size", "type": "int", "label": "总大小"},
        {"key": "avg_file_size", "type": "int", "label": "平均大小"},
    ],
    # deep_analysis
    "kb_health_score": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "namespace", "type": "string", "label": "命名空间"},
        {"key": "activity_score", "type": "float", "label": "活跃度得分"},
        {"key": "index_success_score", "type": "float", "label": "索引得分"},
        {"key": "enable_score", "type": "float", "label": "启用得分"},
        {"key": "summary_score", "type": "float", "label": "摘要得分"},
        {"key": "health_score", "type": "float", "label": "健康评分"},
    ],
    "doc_value_ranking": [
        {"key": "document_id", "type": "int", "label": "文档ID"},
        {"key": "document_name", "type": "string", "label": "文档名称"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "rag_ref_count", "type": "int", "label": "RAG引用"},
        {"key": "head_ref_count", "type": "int", "label": "指定文档引用"},
        {"key": "unique_users", "type": "int", "label": "独立用户数"},
        {"key": "days_since_update", "type": "int", "label": "距更新天数"},
        {"key": "value_score", "type": "float", "label": "价值评分"},
    ],
    "doc_lifecycle_trace": [
        {"key": "document_id", "type": "int", "label": "文档ID"},
        {"key": "document_name", "type": "string", "label": "文档名称"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "index_status", "type": "string", "label": "索引状态"},
        {"key": "index_generation", "type": "int", "label": "索引代数"},
        {"key": "file_size", "type": "int", "label": "文件大小"},
        {"key": "created_at_doc", "type": "datetime", "label": "创建时间"},
        {"key": "updated_at_doc", "type": "datetime", "label": "更新时间"},
    ],
    "user_pattern_evolution": [
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "stat_month", "type": "string", "label": "月份"},
        {"key": "rag_count", "type": "int", "label": "RAG次数"},
        {"key": "head_count", "type": "int", "label": "指定文档次数"},
        {"key": "rag_ratio", "type": "float", "label": "RAG占比 %"},
    ],
    "kb_growth_curve": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "cumulative_docs", "type": "int", "label": "累计文档数"},
        {"key": "cumulative_members", "type": "int", "label": "累计成员数"},
    ],
    "rag_head_verify_rate": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_rag_calls", "type": "int", "label": "总RAG调用"},
        {"key": "verified_by_head", "type": "int", "label": "已验证数"},
        {"key": "verify_rate", "type": "float", "label": "验证率 %"},
    ],
    "user_segmentation": [
        {"key": "segment", "type": "string", "label": "用户分层"},
        {"key": "user_count", "type": "int", "label": "用户数"},
    ],
    # prometheus
    "prom_conversion_success_rate": [
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "success_rate", "type": "float", "label": "成功率 %"},
        {"key": "total_count", "type": "int", "label": "总数"},
        {"key": "success_count", "type": "int", "label": "成功数"},
    ],
    "prom_conversion_duration": [
        {"key": "file_extension", "type": "string", "label": "文件类型"},
        {"key": "p50_seconds", "type": "float", "label": "P50耗时(秒,估算)"},
        {"key": "p90_seconds", "type": "float", "label": "P90耗时(秒,估算)"},
        {"key": "p99_seconds", "type": "float", "label": "P99耗时(秒,估算)"},
    ],
    "prom_active_conversions": [
        {"key": "active_count", "type": "int", "label": "活跃转换数"},
    ],
    "prom_callback_success_rate": [
        {"key": "callback_type", "type": "string", "label": "回调类型"},
        {"key": "total_count", "type": "int", "label": "总数"},
        {"key": "success_count", "type": "int", "label": "成功数"},
        {"key": "success_rate", "type": "float", "label": "成功率 %"},
    ],
    # per-KB detail metrics
    "kb_active_users": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "rag_count", "type": "int", "label": "RAG次数"},
        {"key": "head_count", "type": "int", "label": "指定文档次数"},
        {"key": "total_count", "type": "int", "label": "总次数"},
    ],
    "kb_rag_head_ratio": [
        {"key": "stat_date", "type": "date", "label": "日期"},
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "rag_count", "type": "int", "label": "RAG次数"},
        {"key": "head_count", "type": "int", "label": "指定文档次数"},
        {"key": "rag_ratio", "type": "float", "label": "RAG占比 %"},
    ],
    "kb_zero_chunk_rate": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_queries", "type": "int", "label": "总查询数"},
        {"key": "zero_chunk_queries", "type": "int", "label": "零分块查询数"},
        {"key": "zero_chunk_rate", "type": "float", "label": "零分块率 %"},
        {"key": "low_confidence", "type": "int", "label": "低样本标记"},
    ],
    "kb_retrieval_mode_dist": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "injection_mode", "type": "string", "label": "注入模式"},
        {"key": "call_count", "type": "int", "label": "调用次数"},
    ],
    # quality metrics
    "kb_thin_doc_rate": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_docs", "type": "int", "label": "总文档数"},
        {"key": "thin_docs", "type": "int", "label": "瘦文档数"},
        {"key": "thin_doc_rate", "type": "float", "label": "瘦文档率 %"},
    ],
    "doc_chunk_quality": [
        {"key": "chunk_quality_bucket", "type": "string", "label": "分块质量区间"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    "content_freshness": [
        {"key": "freshness_bucket", "type": "string", "label": "新鲜度区间"},
        {"key": "doc_count", "type": "int", "label": "文档数"},
    ],
    "kb_content_freshness": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_docs", "type": "int", "label": "总文档数"},
        {"key": "fresh_docs", "type": "int", "label": "新鲜文档数"},
        {"key": "fresh_rate", "type": "float", "label": "新鲜度 %"},
    ],
    "duplicate_doc_suspect": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_docs", "type": "int", "label": "总文档数"},
        {"key": "duplicate_docs", "type": "int", "label": "疑似重复文档数"},
        {"key": "duplicate_rate", "type": "float", "label": "重复率 %"},
    ],
    "kb_config_sanity": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "kb_name", "type": "string", "label": "知识库名称"},
        {"key": "issue_type", "type": "string", "label": "问题类型"},
        {"key": "issue_detail", "type": "string", "label": "问题描述"},
        {"key": "config_value", "type": "string", "label": "配置值"},
    ],
    "answer_adoption_rate": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_queries", "type": "int", "label": "总查询数"},
        {"key": "adopted_queries", "type": "int", "label": "采纳查询数"},
        {"key": "adoption_rate", "type": "float", "label": "采纳率 %"},
        {"key": "low_confidence", "type": "int", "label": "低样本标记"},
    ],
    # P3 additions
    "kb_retrieval_hit_rate": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_queries", "type": "int", "label": "总查询数"},
        {"key": "hit_queries", "type": "int", "label": "命中查询数"},
        {"key": "hit_rate", "type": "float", "label": "命中率 %"},
        {"key": "low_confidence", "type": "int", "label": "低样本标记"},
    ],
    "kb_avg_doc_length": [
        {"key": "kb_id", "type": "int", "label": "知识库ID"},
        {"key": "total_docs", "type": "int", "label": "文档数"},
        {"key": "avg_doc_length", "type": "float", "label": "平均大小(KB)"},
        {"key": "median_doc_length", "type": "float", "label": "中位数大小(KB)"},
    ],
    "cross_kb_query_user": [
        {"key": "user_id", "type": "int", "label": "用户ID"},
        {"key": "user_name", "type": "string", "label": "用户名"},
        {"key": "kb_count", "type": "int", "label": "访问KB数"},
        {"key": "query_count", "type": "int", "label": "查询次数"},
    ],
}
