# SPDX-FileCopyrightText: 2025 Weibo, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""
Artifact uploader service for sandbox tools.

Uploads files generated by sandbox tools to the backend storage,
enabling users to download files from chat messages.
"""

import base64
import logging
import os
from dataclasses import dataclass
from typing import Any, Dict, Optional

import httpx

logger = logging.getLogger(__name__)

# Default API base URL for artifact uploads
DEFAULT_API_BASE_URL = "http://wegent-backend:8000"

# Supported artifact file extensions
ARTIFACT_EXTENSIONS = frozenset(
    [
        ".pptx",
        ".ppt",
        ".docx",
        ".doc",
        ".xlsx",
        ".xls",
        ".pdf",
        ".png",
        ".jpg",
        ".jpeg",
        ".gif",
        ".svg",
        ".html",
        ".csv",
        ".json",
        ".xml",
        ".zip",
        ".tar",
        ".gz",
    ]
)


@dataclass
class ArtifactUploadResult:
    """Result of artifact upload operation."""

    success: bool
    artifact_id: Optional[int] = None
    filename: Optional[str] = None
    file_size: Optional[int] = None
    error: Optional[str] = None


class ArtifactUploader:
    """Upload artifacts from sandbox to backend storage."""

    # Default timeout for upload requests (2 minutes)
    DEFAULT_TIMEOUT = 120

    def __init__(
        self,
        task_id: int,
        subtask_id: int,
        auth_token: str,
        sandbox_id: str = "",
    ):
        """
        Initialize artifact uploader.

        Args:
            task_id: Task ID for context
            subtask_id: Subtask ID for linking artifact
            auth_token: JWT token for authenticated API calls
            sandbox_id: Sandbox ID that generated the file
        """
        self.task_id = task_id
        self.subtask_id = subtask_id
        self.auth_token = auth_token
        self.sandbox_id = sandbox_id
        self.api_base_url = os.getenv("TASK_API_DOMAIN", DEFAULT_API_BASE_URL).rstrip(
            "/"
        )

    def _build_upload_url(self) -> str:
        """Build upload URL for artifacts."""
        return f"{self.api_base_url}/api/artifacts/upload"

    @staticmethod
    def should_upload_artifact(file_path: str) -> bool:
        """
        Check if a file should be uploaded as an artifact.

        Args:
            file_path: Path to the file

        Returns:
            True if the file should be uploaded
        """
        _, ext = os.path.splitext(file_path)
        return ext.lower() in ARTIFACT_EXTENSIONS

    async def upload_from_sandbox(
        self,
        sandbox: Any,
        file_path: str,
    ) -> ArtifactUploadResult:
        """
        Upload a file from sandbox to backend.

        Args:
            sandbox: E2B sandbox instance
            file_path: Path to the file in sandbox

        Returns:
            ArtifactUploadResult with upload status
        """
        logger.info(
            f"[ArtifactUploader] Uploading artifact: {file_path} "
            f"(task_id={self.task_id}, subtask_id={self.subtask_id})"
        )

        try:
            # Read file from sandbox
            file_content = await sandbox.files.read(file_path, format="bytes")
            filename = os.path.basename(file_path)

            # Upload to backend
            return await self.upload_bytes(
                file_content=file_content,
                filename=filename,
                file_path=file_path,
            )

        except Exception as e:
            logger.error(f"[ArtifactUploader] Failed to read file from sandbox: {e}")
            return ArtifactUploadResult(
                success=False,
                error=f"Failed to read file from sandbox: {e}",
            )

    async def upload_bytes(
        self,
        file_content: bytes,
        filename: str,
        file_path: str,
    ) -> ArtifactUploadResult:
        """
        Upload file bytes to backend.

        Args:
            file_content: Binary file content
            filename: Name of the file
            file_path: Original path in sandbox

        Returns:
            ArtifactUploadResult with upload status
        """
        upload_url = self._build_upload_url()
        logger.info(
            f"[ArtifactUploader] Uploading to {upload_url}: {filename} "
            f"({len(file_content)} bytes)"
        )

        try:
            async with httpx.AsyncClient(timeout=self.DEFAULT_TIMEOUT) as client:
                files = {"file": (filename, file_content)}
                data = {
                    "subtask_id": str(self.subtask_id),
                    "file_path": file_path,
                    "sandbox_id": self.sandbox_id,
                }
                headers = {"Authorization": f"Bearer {self.auth_token}"}

                response = await client.post(
                    upload_url,
                    files=files,
                    data=data,
                    headers=headers,
                )

                if response.status_code == 200:
                    result = response.json()
                    logger.info(
                        f"[ArtifactUploader] Artifact uploaded successfully: "
                        f"id={result.get('id')}, filename={result.get('filename')}"
                    )
                    return ArtifactUploadResult(
                        success=True,
                        artifact_id=result.get("id"),
                        filename=result.get("filename"),
                        file_size=result.get("file_size"),
                    )
                else:
                    error_msg = f"HTTP {response.status_code}: {response.text}"
                    logger.error(f"[ArtifactUploader] Upload failed: {error_msg}")
                    return ArtifactUploadResult(
                        success=False,
                        error=error_msg,
                    )

        except httpx.TimeoutException:
            error_msg = "Upload timeout"
            logger.error(f"[ArtifactUploader] {error_msg}")
            return ArtifactUploadResult(success=False, error=error_msg)
        except Exception as e:
            error_msg = f"Upload error: {e}"
            logger.error(f"[ArtifactUploader] {error_msg}")
            return ArtifactUploadResult(success=False, error=error_msg)
