# SPDX-FileCopyrightText: 2026 Weibo, Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""Internal data analysis endpoints for DuckDB artifact storage.

Provides endpoints for knowledge_runtime to upload generated .duckdb files
as new SubtaskContext attachments. These endpoints are intended for
service-to-service communication only.
"""

from __future__ import annotations

import logging
from typing import Optional

from fastapi import APIRouter, Depends, File, Form, UploadFile
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.api.dependencies import get_db
from app.services.auth.internal_service_token import verify_internal_service_token

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/data",
    tags=["internal-data"],
    dependencies=[Depends(verify_internal_service_token)],
)


class DataArtifactUploadResponse(BaseModel):
    """Response from .duckdb artifact upload."""

    attachment_id: int
    success: bool
    error: Optional[str] = None


@router.post("/artifacts/upload", response_model=DataArtifactUploadResponse)
async def upload_data_artifact(
    source_attachment_id: int = Form(
        ...,
        description="Original attachment ID that the .duckdb was generated from",
    ),
    file: UploadFile = File(..., description="The .duckdb file binary"),
    db: Session = Depends(get_db),
) -> DataArtifactUploadResponse:
    """Upload a .duckdb artifact file generated by knowledge_runtime.

    Creates a new SubtaskContext attachment record with the .duckdb binary data.
    The source_attachment_id is stored in type_data for traceability.
    """
    from app.services.context.context_service import context_service

    try:
        # Read the uploaded file bytes
        duckdb_bytes = await file.read()
        if not duckdb_bytes:
            return DataArtifactUploadResponse(
                attachment_id=0,
                success=False,
                error="Empty file uploaded",
            )

        filename = file.filename or f"duckdb_{source_attachment_id}.duckdb"

        # Ensure .duckdb extension
        if not filename.endswith(".duckdb"):
            filename = f"{filename}.duckdb"

        # Upload as a new attachment using ContextService
        # Use user_id=0 since this is a system-to-system upload
        context, _ = context_service.upload_attachment(
            db=db,
            user_id=0,
            filename=filename,
            binary_data=duckdb_bytes,
            subtask_id=0,  # Unlinked - will be linked when needed
        )

        # Add source attachment metadata to type_data
        type_data = context.type_data or {}
        type_data["source_attachment_id"] = source_attachment_id
        type_data["is_duckdb_artifact"] = True
        context.type_data = type_data
        db.commit()
        db.refresh(context)

        logger.info(
            "DuckDB artifact uploaded: id=%d, source_attachment_id=%d, size=%d bytes",
            context.id,
            source_attachment_id,
            len(duckdb_bytes),
        )

        return DataArtifactUploadResponse(
            attachment_id=context.id,
            success=True,
        )

    except Exception as e:
        logger.exception("Failed to upload DuckDB artifact: %s", e)
        return DataArtifactUploadResponse(
            attachment_id=0,
            success=False,
            error=str(e),
        )
